---
title: 广告
weight: 3034
slug: 好好学习天天向上/广告
目录:
  - 04好好学习天天向上
标签:
  - 2024年
---
最近经常看到各式各样的招生广告。

这类广告的意义自然在于，显出一位教授及其实验室的优秀之处，希望能够尽量吸引水平更高的学生来就读。

但是我自从到多伦多大学工作以来，从来没有发过招生广告。

一来我一直认为优秀的教授如同限量版的保时捷一样，无论从他们的时间和经费来源来看，一辈子总共能招收的学生都极其有限，属于一种稀缺资源。比如斯坦福大学著名教授 Donald Knuth，图灵奖获得者，据说其学术生涯一共仅仅指导了 28 个学生。所谓「好酒不怕巷子深」，当「好酒」的香气口口相传远远地飘过来，自然就不需要在胡同口放一块用于引流的广告牌。

二来我虽然没有发过正经八百的招生广告，却多年一直在写属于我自己风格的「广告」—— 我的文字，我的微博，它们就是我的广告。喜欢我的文字的学生读者，如果恰巧也对我的专业方向感兴趣，我虽然没有明说，却是很希望他们能来占用我这里的「稀缺资源」的。也正因为如此，如果学生在「套瓷信」里提到了我以前的文字，我经常会另眼相看，绝对是一个加分项。

但是最近有些事儿让我觉得，其实正经八百发一则招生广告也是一个不错的主意。

我以前一个学生，现在在香港当教授。她收了一个博士生，刚刚读了半年，直接退学了。

无独有偶，我自己的一位博士生，恰巧在教师节的今天，跟我「官宣」不读博士了，准备转为课程型硕士学位毕业，已经开始找工作了。他退学的原因是想早点儿到工业界找工作，早点儿赚大钱。

如果一个学生在决定退学去工作之前问我的意见的话，我会跟他说，人的一生很长，其实不用特别着急打卡上班挣钱。博士学位虽然在读期间会损失不少工资收入，将来毕业了也并不能保证挣到更多的钱，但是博士研究是一种在痛苦中创新的过程，而创新则需要用语言文字交流沟通的能力，也同时需要较强的理论基础和动手能力。试图做研究写论文的过程，就是提高自己领导、沟通、总结、动手和理论推导能力的过程。而这些能力无论将来做什么都挺重要的。

所以我想写一则招生广告。

以前有些人问我，招收学生有什么标准，如何择优录取。我的标准一直挺简单的：数学、英文和编程能力这三项，有一强项即可，如果有俩强项，那就相当罕见了。所以我其实并没有真的「择优」录取，甚至有不少随意的成分。主要是因为我觉得吧，一位水平可以算是「稀缺资源」的教授，其真正的「产品」，不是他的荣誉，也不是他的论文，而是他培养的学生。如果一个学生本来就是天才，那即使不怎么培养，他依旧还是天才，并不能体现教授的水平。而如果一个学生本来基础薄弱，什么都不会，毕业时成为了一名可以胜任大学教职的合格人才，那才能体现这位教授培养人才的水平。

再过两个月我就五十三岁了。可能将来退休之前，没有太多的精力和时间培养很多学生了。如果你是一位学生读者，觉得我属于我自己说的「酒香不怕巷子深」的稀缺资源；如果你数学、英文和编程至少有一项还比较拿手；如果你看过我以前写过的文字，跟我的想法挺有共鸣；如果你同意我「人的一生很长，不用着急打卡上班赚钱」的观点的话，欢迎你来申请加入我在多伦多大学的研究小组，攻读博士学位。

是为广告。

<div align=right>
2024 年 9 月，多伦多
</div>
