---
title: 芝麻开门
weight: 3037
slug: 好好学习天天向上/芝麻开门
目录:
  - 04好好学习天天向上
标签:
  - 2025年
---

>冒昧打扰，首先感谢您在微博上分享的内容，我偶然间刷到您的主页，被每一篇文章深深打动，感受到您对学术的热爱与深邃的思考，令我受益匪浅。恰逢今年我也刚刚进入多伦多大学电子与计算机工程专业攻读硕士（授课型），在适应新环境的过程中，我对AI尤其是大模型方向产生了更为浓厚的兴趣。在查阅资料与了解学界动态的过程中，得知您在相关领域有着深厚的研究积累和出色的成果，因此斗胆写信向您咨询，不知是否有机会参与您的课题组或项目，哪怕是以协助的方式，也非常愿意从基础做起，跟随您学习、积累经验。（问题来着微博留言）

前几天，恰巧有机会见到苏黎世联邦理工学院（ETH Zurich）计算机网络领域的著名教授 Adrian Perrig，聊了几次天儿。

Adrian Perrig 教授有多厉害呢？

他在谷歌学术上的 H-index 高达 106，相当于有 106 篇论文引用数在 106 以上。H-index 的特点是，它越高，就越难以继续上升。research.com 显示，根据 H-index 排名，他在计算机科学领域是瑞士第十一位。由于计算机网络领域是一个相对比较冷门的领域，他这样的 H-index，已臻「惊为天人」的水准。

我们「宾主就共同关心的话题，广泛地交换了意见」。比如我们俩都对异步 Rust 编程中的并发机制感兴趣，尤其对于多协程并发时是否应该对数据结构加锁和如何加锁的问题，讨论得还挺深入。

有一次我们吃饭，正好聊到了「套瓷」信如何写的问题。发现我们俩的观察和发现几乎完全独立，却有异曲同工之妙：我们都极少 —— 如果高标准严要求的话，甚至从来没有 —— 收到过令人眼前一亮的套瓷信。

那什么才是令人眼前一亮的套瓷信？

首先，无论是中文还是英文，一封套瓷信可以直接展现作者的文笔。写套瓷信和写论文一样，应该从自己的姓名开始，开门见山，言简意赅，有自己独到的文风。相对而言，大模型写出来的文字，往往显得过于正式而平庸，没有自己的特点。这就是我为什么希望学生尽量不要用大模型 —— 用的时间一长，即使自己亲自写，也可能永远写不出文采飞扬的文字来了。

其次，套瓷信需要有「点睛之笔」。

什么是「点睛之笔」呢？

这个「点睛之笔」的特别之处在于，简单一看，就可以知道这封套瓷信是专门给收信人写的，不可能发给其他任何人。

比如，Perrig 教授十几年如一日，潜心研究和推广下一代全球互联网的设计和实现，名字叫做「SCION」。他为了 SCION 的推广，花费了大量心血和时间，甚至亲自写代码、写书、写用户手册。

然而他发现，收到的套瓷信中，极少有提到 SCION 的，更不用说提到其中设计和实现的细节。甚至可以说，只要套瓷信中提到了这个词儿，他都会另眼相看，至少会花时间回复邮件。如果还能深入浅出地提到其中关键的设计亮点 —— 比如同时采用大量路径的多路径传输 —— 那「套瓷」的成功率就更高了。

原因很简单：连套瓷信都能如此认真对待的学生，将来对研究也多半儿会对细节极其重视。而因为提到「SCION」的学生极其罕见，也突出了作者特立独行、和别人迥然不同的品质。

这就如同《一千零一夜》中那篇家喻户晓的阿拉伯民间故事《阿里巴巴和四十大盗》里，阿里巴巴对着藏宝的山门喊出的暗语：

芝麻开门。

<div align=right>
2025 年 7 月，香港
</div>
