---
title: 答案
weight: 23
slug: 幸福/答案
目录:
  - 01幸福
标签:
  - 2020年
---
李老师，越来越多的人开始提到或者接受「世界不是非黑即白，看问题不能二元对立」的看法，我也很赞同这个看法，但一直找不到合适的语言描述世界不是非黑即白，那到底是什么样的呢？我们又该在这样的世界里以什么样的勇气和信念生活下去呢？ 希望听听李老师的看法。（问题二月二十七日来自微博私信）

李老师我又来问问题啦！想请问李老师，在和父母长辈交流有不同观点时，有比较可行又不伤害对方的方法吗？我知道很难改变一个人的对某件事情的看法。如果是其他人，我根本就不在乎，反而还是一个筛选出那些不同想法的人的机会。但和亲密的人长期有思想上的隔阂又让我很难过。（问题九月十三日来自微博私信）

##### 一

看问题时是该非黑即白，坚定立场，还是该「萝卜白菜各有所爱」，那得看这提的是个什么样儿的问题。

比如说，如果你的问题是「地球是不是圆的」或者「吸烟是否对健康有害」，那我当然应该斩钉截铁地给出一个正确的回答，因为可以用科学的方法明确得出正确的结论。

如果对方辩友反驳说，我认识个老爷子抽了一辈子烟，还不是活了八十多岁？我自然可以告诉他，不能用具体的个例来推翻统计上的规律 —— 保险公司在卖人寿保险时抽烟的人保费更高，正是直观地表现了这种统计规律。

但如果你的问题是「刘亦菲是不是比 Angelababy 更漂亮」，那当然就仁者见仁、智者见智，没有正确错误之分，没什么可争的。不但没什么可争的，这样的话题还是闲聊中万一断了话题可以用到的谈资：「哎你最近看《摩天大楼》和《花木兰》了吗？你觉得刘亦菲更好看还是 baby 更漂亮？」如果大家正好都是刘亦菲或者 Angelababy 的粉丝，话题跟香槟酒似的正好续上，火热继续。

这两种问题性质完全不同，有点儿像我小时候看过的报纸。那时报纸不多，经常能看到的有两种：《参考消息》和《北京晚报》。

《参考消息》虽然经常看到，但是我不怎么爱看。主要是因为那里面每一篇文章都很简短，不外乎就是些国际国内的大事儿，没有任何带一点儿感情色彩的评论。这就有点儿像第一种问题，黑的就是黑的，白的就是白的，泾渭分明。

而《北京晚报》则有点儿像现在的今日头条，社会万象，娱乐花边新闻，可以看得很过瘾。夏天搬个小马扎儿拿上一份儿《北京晚报》到阳台，凉风习习，越看越爱看，惬意的很。这就有点儿像第二种问题，「站」不「站」肖战无关紧要，只要知道《陈情令》中有个叫魏无羡的人，咱就大有可以聊的话题。

这第二种问题，「友谊第一，比赛第二」，无所谓谁赢谁输。就像照着菜谱炒菜，「放盐、糖、味精各少许，翻炒至八成熟」—— 不用这么精确，模棱两可，开心就好。而第一种问题则不然，关乎自然科学或者社会科学中的素养，不懂当然没有问题，也可以拿来争论不休，但是无论如何，客观上答案只有正确的和错误的两种，没有中间路线。把它「佛系」地当成第二种问题来含糊其辞，号称「看问题不能二元对立」，是完全错误的。

##### 二

那如果是第一种问题，正确答案从何而来呢？

Netflix 上最近上映了一部纪录片叫《The Social Dilemma》，如果你没看过，值得花时间看一看。很多人看了觉得触目惊心，可我看了没觉得很意外啊，说的不就是今日头条嘛 —— 你爱看什么，社交媒体平台就有更多的类似内容会推送给你，你就会越来越相信你对这个问题的见解是正确的。

比如「地球是不是圆的」这样的问题，如果你在社交平台上看到论证「地球是平的」的文章，会发现里面摆事实、讲道理，证据确凿，言之有物，看多了一定会越来越相信地球其实是平的。你还别说，相信地球是平的的人还挺多 —— 美国每年都专门召开个会议，就叫「平地球国际会议」(Flat Earth International Conference)，有点儿粉丝后援团聚在一起开展活动的感觉。

我认为，与其到网上随手「刷」一些支持自己立场和观点的推送文章，不如去「特别关注」一些高水平的作者写的文字。高水平的作者虽然平时写的文章不一定很多，但是一旦下笔，如果回答的是第一种问题，其文字中的观点一定逐字逐句地仔细推敲琢磨过，力求客观、符合历史规律。

高水平的作者不经常在他们不熟悉的领域发表见解。他们会抱着学习的态度，不会不懂装懂，对每一种观点都充分怀疑，去伪存真。著名哲学家罗素 —— 就是《围城》里褚慎明亲切地称为 Bertie 的那个罗素 —— 就曾经说过：「这个世界上的一大问题是，傻子和狂热的人永远认为自己正确，而聪明人则满满地全是怀疑。」(The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.)

所以说，即使是高水平的作者写出来的文字，我们也不能照单全收，而是应该自己静下心来仔细想想他说的是否真的有道理，逻辑上有没有问题，甚至用科学的方法从侧面调查研究一下支持其观点的论据是否可靠。

我所敬仰的经济学家 Thomas Sowell 曾经说过：「意识到自己的无知，需要不少知识。」(It takes considerable knowledge just to realize the extent of your own ignorance.)

遗憾的是，在这个「人工智能」的大时代，往往越是罗素或者 Thomas Sowell 这样相当靠谱的作者，写出来的文字看过的人就越少。

##### 三

那如果和父母或亲友对一个问题的看法完全不同，该怎么办？

最近金斯伯格 (Ruth Bader Ginsburg) 去世了。这位金斯伯格大法官是位传奇般的人物，一生非同凡响。两年前有一部叫《On the Basis of Sex》的电影非常好看，刻画过她的生平。我还发现老太太非常热爱运动健身，写作风格则既浅显又简练，这一点比 Thomas Sowell 强不少：Sowell 的著作篇幅往往都很长，最著名的《Basic Economics》这本书看到后来，都有点儿车轱辘话来回说的感觉了，浅显易懂没有问题，但完全谈不上简练。

金斯伯格婚礼那天，她的婆婆给了她一条忠告：「In every good marriage, it helps sometimes to be a little deaf.」（一桩好的婚姻中，稍微有点儿耳背是好事儿。）

金斯伯格说，她的婚姻五十六年，一直都是这样做的。即使是在最高法院的工作中，她也将这句话奉为信条：就算别人说的不对，也最好「这耳朵进，那耳朵出」。

我想，老太太可能是在说，每个人都在走他喜欢的那条路，而即使是至亲的人，你也很难改变他自己选的那条。

这让我想起了我喜爱的电影《花木兰》里的一句台词：

Take your place, Mulan.

<div align=right>
2020 年 9 月，香港
</div>

