---
title: 百度
weight: 5021
slug: 为祖国健康工作五十年/百度
目录:
  - 06为祖国健康工作五十年
标签:
  - 2019年
---
看到微博里有国外的老师回国工作，抱怨百度不好用。恰巧我前一阵子也回国教了一门短期课程，惊喜地发现百度其实并不是一无是处。

比如上周因为备课需要，我想安装 PyTorch + Python 3.7 的最新版本。正常情况下，应该是命令行一个命令，再等一杯咖啡工夫的事儿。结果我花了一整个晚上的时间一次一次地尝试，为了下载一个几十 MB 的 PyTorch 安装包。不但进度极其缓慢，而且下到一半儿就断了，下次必须重新下载。

我有点儿不服气：作为一名学计算机专业的博士，修不了 Windows 也就罢了，连一个安装包都下载不了，水平未免也太低了吧。

这时我竟然莫名其妙地想到了百度。我用百度直接搜索安装包的名字，第一个链接就是清华大学的镜像网站。从这个网站下载，十几秒钟就顺利完成了，解决了一大疑难问题。

不过也别高兴得太早了。课程结束后我到北京转机回加拿大，转机时间较长，计划进城看望一下父亲。我抱着试试看的态度，用百度地图搜索从机场去马甸桥的最佳公交线路。百度地图告诉我，最好的办法是机场快线去三元桥，然后出站转 847 路。我听说机场快线需要现金才能买票，还专门找了一个取款机取了现金，做好了上路前的充分准备。

到了三元桥站，我发现情况有点儿不妙。三元桥站有 A、B、C1、C2、C3 五个出站口，没有任何标识说明哪一个出站口出来可以坐公交车。跟着百度导航出站，发现是一个错误，只好再重新回到地铁站里，换一个出站口出站。运气不太好，换到第三个出站口才找到 847 路公交车站。等了好一会儿没来车，只好放弃了这个「小试验」，后一半儿行程改成打车。

打车时发现百度地图里也可以叫车 —— 不过这时我已经没有「探索未知世界」的心情了。我打开「滴滴」，车一会儿就到了，仿佛又回到了自己熟悉的「地盘」。

回到加拿大，又想起了这件小事儿。「完美主义」使然，我又做了一点儿调研。结果发现百度开始的建议就是错误的：最好的办法是坐去公主坟方向的机场大巴，可以直接在马甸桥站下车。看来即使在这个「大数据」和「人工智能」的时代，还是不能完全依赖「临阵磨枪」，还是要事先做好调研，取好现金，才能「学好数理化，走遍天下都不怕」。

<div align=right>
2019 年 7 月，多伦多
</div>
