---
title: 论文
weight: 3029
slug: 好好学习天天向上/论文
目录:
  - 04好好学习天天向上
标签:
  - 2023年
---
刚接到通知，我和王菲合作的论文得到了 IEEE INFOCOM 2023 的最佳论文奖（Best Paper Award）。

二十多年来，我一共在 IEEE INFOCOM 这个计算机网络方向的国际会议上发表了八十篇论文。根据上海交通大学王新兵教授独创的 [AceRanking](https://www.acemap.info/ranking) 网站，以 2000 年以来 INFOCOM 论文的引用 H-index 计算，我排行第一位。

可我从来没有得到过 INFOCOM 的最佳论文奖，这次是头一回。

不过这丝毫不稀奇：会议每年录取两百多篇论文，只有一两篇可以得到最佳论文。按照概率计算，绝大多数学者一辈子也得不到一次。

我一直觉得，一篇理想中的论文应该像一件精心设计打磨的手工作品，需要从选题到实验，从行文到插图，不慌不忙，慢工出细活。论文的作者则各司其职，通力合作。

王菲这篇题为「More than Enough is Too Much: Adaptive Defenses against Gradient Leakage in Production Federated Learning」的得奖论文，历时四个月，三个作者完美合作，缺一不可，基于我这之前一年多来自己写的联邦学习开源框架，实现了我关于论文写作的理想。

论文的选题其实是因为我们实现已有的隐私保护方面论文时，发现这些论文的结论都是错误的。

说它们错了其实也不是特别准确。准确地说，它们把联邦学习理解错了 —— 它们的假设在实际中并不成立。由于这些错误的假设，它们的隐私保护机制过于浓墨重彩，就像开着保时捷 911 去自由市场买菜，远不如骑辆永久二八自然。

我记得当时看到我们的初步试验结果，王菲同学大笔一挥，为她的 [第一篇 INFOCOM 论文](https://iqua.ece.toronto.edu/papers/feiwang-infocom23.pdf) 题名：

More than Enough is Too Much.

就如同她爱说的名言：想多了。

<div align=right>
2023 年 4 月，多伦多
</div>

