---
title: 比特币（三）
weight: 7029
slug: 柴米油盐酱醋茶/比特币三
目录:
  - 08柴米油盐酱醋茶
标签:
  - 2021年
---

> 李老师您好。比特币仿佛又迎来了新的春天，我这样不太懂的人很难分辨购买比特币是投资还是投机，打算用小部分闲钱购买比特币等数字货币基金并长期持有。想知道您对比特币这类数字货币的未来怎么看？（问题来自微博私信）

##### 一

我一直认为，如果对一件事儿不是很了解，应该先花时间做一些调查研究，再去做决定。

比如打算买一辆新车，是买丰田还是买特斯拉？虽然当今买特斯拉比较时髦，我经过一段时间仔细的研究，还是决定买一辆丰田。

买车完全可以看心情，但是投资不同，由于关系到几十年以后的生活品质，花点儿时间做研究是相当合算的。我说的针对投资的研究，不是简单地看看微博上「大 V」关于特斯拉比特币的新鲜观点，而是从关于股票和债券的基本知识开始，读一读 Benjamin Graham 写的《The Intelligent Investor》或者 Warren Buffett 写的《Letters to Shareholders》，再追一追三十年前的股神 Peter Lynch 或者还继续活跃在投资第一线的 Michael Burry，你的研究工作才算是全面而深入。

你发现没有，我所推崇的研究不是去被动地去刷每天推送给你的内容，而是自己主动地去筛选和寻找高质量的信息，甚至去读几十年前写的书。每天社交媒体的新闻很容易让你觉得机会再不抓住就一去不复返了 —— 英文叫 Fear of Missing Out (FOMO)。无论是买房、买特斯拉还是买比特币，一旦有了这种「FOMO」的焦虑，早晚会有「all in」的冲动。偏爱「赌一把大的」迅速达到「财富自由」，是我们大家都有的美好理想。

三十多年前巴菲特有一次访谈中曾经提到过一个观点叫「tune out the noise」。说的就是在如今信息爆炸的时代，应该尽量少看短期的新闻和投资分析，而是去研究一家公司长期的价值。那时的 IBM 有点儿像现在的特斯拉，是高科技领域的新宠，而巴菲特没有买 IBM 的股票，一是因为他不懂高科技，无法准确地评估这家公司的价值；二是他完全不怕「Missing Out」：一个人再努力也不可能什么都懂，错过了自己不懂的机会有什么可遗憾的？

所以，与其天天「FOMO」，我提倡「Fear of Mixing In」(FOMI)—— 一去不复返的机会没有抓住没关系，我更害怕随波逐流，人云亦云。

##### 二

几十年长期投资需要考虑的因素中，最重要的是风险。

风险的种类有很多。比如如果只买一家公司的股票，会有投资过于集中的风险（concentration risk）。

假设你花了一万块钱买了比特币或者特斯拉，将来如果有一天中央银行限制了比特币的流通，或者电池生产的原材料紧缺，你的一万块钱就有可能大幅度缩水。

所以，现在分散风险的常规做法是买入 Exchange Traded Funds (ETF)，相当于你这一万块钱同时投资了几十、几百、甚至几千家公司的股票，涵盖了不同的市值、不同的产业、甚至不同的国家和地区，而不是只买一家公司的股票。

花一万块钱去买比特币，自然也会有投资过于集中的风险。

那如果我有十万块钱，只拿其中一万块去买比特币，不怕什么投资集中的风险，是不是就没问题了？

咱找一家历史悠久的加拿大公司 —— Enbridge Gas —— 来横向比较一下。Enbridge Gas 的业务很多，主要的一项业务是石油运输管道（比如其著名的 Line 3 pipeline）。就好像我们每天都离不开手机一样，无论油价高低，石油总是要通过管道运输的。由于新建管道越来越困难，已有的管道也就可以旱涝保收，越来越重要。正因为这个原因，以 Enbridge Gas 现在每股 35 美元的价格，每年的分红是 7.36%。

如果你把每年投资 Enbridge Gas 的分红拿来继续买入这家公司的股票，三十年以后，你投资的一万块钱，可以涨到八万四千元。

由于比特币不是公司，所以没有分红。三十年以后，比特币如今 46000 美元的价位，需要涨到三十九万美元，盈利才能超过投资 Enbridge Gas。

比特币有没有可能涨到三十九万美元呢？当然有可能。不但三十九万美元有可能，三千九百万美元都有可能。但是它也有可能三十年后无人问津，一文不值。而 Enbridge Gas 的石油运输管道，三十年后一定还在继续运营。虽然投资比特币潜在的收益很高，但承担的风险更高。你可以选择投资比特币，但是你的选择不应该是人云亦云，而是完成了上述研究之后才得出的结论。

我选择 Enbridge Gas —— 而且宁愿错过比特币这个说不定千载难逢的历史机遇。

##### 三

如果你打算买比特币的话，最好先确认一下你买的确实是货真价实的比特币。

如果你去买基于比特币的基金或者 ETF，那么你这一万块买到的其实是一种衍生产品：你的比特币不属于你，而是属于基金公司 —— 最多算是基金公司替你代持。

那你研究过没有，如果该基金公司的比特币哪天被人偷走了，或者基金公司自己倒闭了，怎么办？

这就是所谓的 counterparty risk: 基金公司作为中间人替你去买比特币，那你就必须多承担一点儿风险。理论上来说，基金公司可以将其管理的比特币找保险公司投保，那你的风险就相应转化为保险公司是否会理赔的风险，风险就有可能大大降低。

但是我的研究表明，绝大多数基金公司并没有为其管理的比特币买任何保险。既然你是打算长期持有比特币，这样的风险不可忽略。

所以如果你想买的是货真价实的比特币的话，我强烈建议你仔细研究一下有关区块链技术和比特币交易的知识，把你买来的比特币用一个硬件钱包（hardware wallet）离线「冷藏」（cold storage）起来。

这样一来，你就可以避开任何有关基金公司代持的风险，唯一的要求是你必须记住一条二十四个单词组成的短语，做为你拥有比特币的专属密码。

这二十四个单词太重要了：谁有了这条短语，谁就有可能卖掉你的比特币。所以你不能存在电脑中，不能上传到云服务器，也不能写在纸条上放到保险箱里 —— 你必须死记硬背下来，保证未来的三十年中任何时候都记忆犹新。

我在研究比特币的过程中，还真的为这小小的二十四个单词从何而来的细节犹豫了半天。

最终我决定，如果我买比特币，应该把它存在一首我最为熟悉的宋词中：

「遥想公瑾当年，小乔初嫁了，雄姿英发。羽扇纶巾，谈笑间、樯橹灰飞烟灭。故国神游，多情应笑我，早生华发。人间如梦，一樽还酹江月。」

<div align=right>
2021 年 2 月，香港
</div>

