---
title: 忙
weight: 5027
slug: 为祖国健康工作五十年/忙
目录:
  - 06为祖国健康工作五十年
标签:
  - 2020年
---
> 李老师，昨天跟一个小学同学见面，很有感触，想跟您聊聊。
>
> 她家境不错，学业认真，人品也很好，一路顺利进入一个国内 985，想着毕业就出国，但毕业前夕因为家庭变故，她「忍痛」留在家乡一个国企工作至今。毕业这两年，每次春节回家同学聚会，她不是在学习就是在考证，都不来。我觉得她太不轻松了。很多人轻而易举、云淡风轻的事情，在这位同学这里，似乎是不得了的高山，而她会特别努力，去攀登越过，再追求一座更高的山，更难的问题。
>
> 半年过去，这位同学从地方国企总部，跳到了一个分部。现在她每天的生活很忙，虽然每天焦头烂额一度抑郁，但因为现在的工作是随时有突如其来的麻烦、突如其来的新问题要解决。所以虽然很紧张，但也很刺激。之前在国企总部，属于每天做一模一样的工作，毫无变动。所以这种忙碌感，让她觉得很充实，并认为充实的日子让人内心很健康，感觉每天都在释放自己。
>
> 不知道李老师怎么看待「忙碌是无所事事者的避难所」这句话。对比之前有大把时间但是很焦虑，现在的她很忙但是很充实。作为朋友我为她高兴，但还是不能理解这种状况。不知道李老师怎么看。（问题来自微博私信）

##### 一

说起「忙」这个话题，我想到了外公的杂文集《龙虫并雕斋琐语》中的一篇文章，题目就叫《忙》。

外公将「忙」分为三种。青年时代除了读书之外，体验的是恋爱之「忙」：

> 恋爱的青年有闲中之忙，有忙中之闲。所谓闲中之忙，是因为游山玩水，步月赏花成为一种功课，一种手段，你闲也要你闲，你不闲也要你闲。这样的情形，我们可以叫做「忙于装闲」。

而人到了中年，却又该为事业而忙了：

> 恋爱的忙，虽忙不苦；事业的忙，有时候既忙且苦。当然，以一身系天下安危的人，多忙一分，则民众多受一分的德泽；就是为自己而忙，只要忙得有意思，忙得有新花样，忙得顺利，也就高兴去忙。不过，世界上高兴忙的人实在太少了，苦忙的人也实在太多了。

那你可能会问，等到事业有成，是否就可以不忙了呢？在外公的笔下，「忙」中的最高境界是为了应酬而忙：

> 一个人得到了社会所知以后，似乎他的世界就应该被社会所糟蹋。这一种忙，忙得最苦。既不为食，又不为色，只为的是怕得罪人。我们家乡有一句俗话说：「三十又忧名不出，四十又忧名不收。」古人入山唯恐不深，就是「收名」之道；如果你「自嗟名利客，扰扰在人间」，随便怎样苦忙，也只算是自作自受了。

哈哈，如果你现在正在为应酬而忙，那恭喜你事业有成了。

##### 二

「忙」本身不是问题，但是忙得上了瘾就不妙了。

什么叫忙得上了瘾呢？

有的时候一个人实在太忙了，忙得稍微闲下来一点儿就坐立不安；忙得而没有时间把任何一件小事儿做得完美、做得精益求精。

而如果做点儿事儿一直捉襟见肘，无法静下心来精心完成，最后很可能功亏一篑，一事无成。

比如，一位教授接受了邀请，需要在一次会议上做一个报告。而因为他太忙，没有时间准备报告的幻灯片和演讲稿，只得责成其学生帮他准备，他上台念一下就可以了。一次两次这么做虽然不雅，也无可厚非；但是如果常年如此，这位教授就会渐渐失去了独立思考和写作的能力，脱离了真实的环境。以致很可能演讲时经常望文生义，无法应对现场针锋相对的提问，「知其然不知其所以然」。那这位教授有没有可能自己准备演讲稿、甚至脱稿演讲呢？其实如果他可以回绝一些为了应酬的「忙」，是完全可以做到「自力更生」的。

所以说啊，稍微忙点儿虽然挺好，但忙得上了瘾不提倡。有的人把自己折腾得太忙了，是因为他们对将来的期望有点儿太高。绝大多数人没有马斯克的天分和马云的机遇，即使跟他们一样忙，天天想着跟他们一样创业，也很难「改变世界」。也有些人太忙，是因为过于重视别人对他的看法，怕得罪人。别人都忙着加班，他虽然觉得加班很累人，也跟着加班；别人都忙着玩创业，他虽然没有创业的灵感，也跟着玩创业。当他们忙着「释放自己」、忙得上了瘾时，日子疾驰而过，会错过很多美丽得令人心动的瞬间，错过了就再也回不来了。

「忙」很像看电视。看得时候很开心很充实，但是看得太多看上了瘾，就逐渐忘了还可以在街边杀一盘象棋，还可以抱一把吉他自弹自唱，还可以什么都不干，任由光阴从眼前流逝。

##### 三

一个多月前，我正收拾好行装准备赶往机场飞香港的途中，不意间收到了一条微信。

是一位很少联系的朋友发来的一句简短的问候：「你们还好吗？」

我秒回：「还挺好的，正好今天早上要飞香港。」

对方没有再回信。

我简单想了想，这一天好像不是端午节，也不是双十一不是五二〇不是六一八不是七夕不是任何网红或传统的节日。

也许是我的结交面儿太窄，我已经不记得上次有朋友还没到节假日就给我发来简单的问候是什么时候了。

也许是因为我们都太忙，忙得没有时间也没有心情，忙得很难忽然没来由地就想起远方的朋友来。

那天早晨的这样一句简单的问候，让我怦然心动。

<div align=right>
2020 年 8 月，香港
</div>