---
title: 量力而行
weight: 7026
slug: 柴米油盐酱醋茶/量力而行
目录:
  - 08柴米油盐酱醋茶
标签:
  - 2020年
---
> 李老师新年好。看过您的一些回答，觉得回答中肯，都很有参考价值。我最近的问题是这样的：和女朋友已经相处一年多了，近日她又对我讲买房子的事情，大意是婚前我要买一套属于自己的房子，哪怕小户型也好。
>
> 因为她自己的同事们要么结婚要么在深圳周边的城市如东莞都买房供房了，她的意思是如果现在不咬牙买下今后就更加买不起了。我们都是工薪族，我比她大好几岁，职业发展一般。之前谈到买房的话题时两个人还闹过矛盾，因为我对买房有点抵触，不想在婚前就背负房贷做房奴，可是买房对她来讲就是安全感的所在。我也不懂什么投资理财，房子用她的话讲就是一个可以升值的商品，比把钱存到银行要强很多。
>
> 我不想跟她就买房的问题再有矛盾，请问李老师，我怎么在大方向去规划买房这件事，不是不买，也不是跟风似的买。谢谢。（问题来自微博私信）

房子当然可以买，不过你们最好能先大致了解一些买房的常识再买。这样无论将来出现什么问题，不至于因为房子的事儿影响两个人的感情。

从几十年的长期来看，买不动产虽然不能像你女朋友说的那样保证可以升值，但是确实是有可能可以保值的。也就是说，随着货币的贬值，房产的纸面价值不断上升，而其购买力则大致保持不变。这是因为随着时间的推移，房子本身是贬值的，但房子所在的地段和社区逐渐成熟，地价逐渐升值，两者相抵，房产基本保值。

要是想长期投资可以升值，其实应该投资股市。这是因为如果资本市场非常成熟，从长期来看，投资股市的一部分钱是用来扩大再生产的，确实创造了新的价值。

当然，几十年的长期不确定因素太多，没有人可以预测。比如如果二十年前在美国买房，其投资收益远远不如把同样的钱投资美国股市。但如果换到国内，结果则恰恰相反：二十年前投资股市远远不如买房。

但是投资有一个常识：以往的投资表现不代表未来。说不定下一个二十年应该反过来在美国买房、在国内投资股市呢。世界上房价不升反降的例子比比皆是。比如日本东京的房价自从九零年崩溃之后，由于人口逐渐老化，到现在三十年了，都没能完全恢复当时的最高点。但凡有人告诉你买房长期可以升值，你就得好好考虑一下他这么说的动机。

所以说，买房不应该是为了投资升值，而是为了你女朋友提到的「安全感」。住在自己买的房子里会比住在租来的房子里感觉更安心、更幸福，这是人之常情。为了这样的「安全感」买房，我认为很值得。

所以说，买房不是为了投资，而是在买一样儿给自己多一点儿幸福感的商品。这一点和买车、买手机其实差不多，唯一的区别是房子比车和手机贵得多，需要几十年收入的很大一部分慢慢才能还清。

就是因为买房贵得多，所以就需要慎重地计算一下你的收入到底可以买多少钱的房子。这个道理其实很浅显：比如如果你只能买得起丰田汽车，你绝对不会去买什么「奔驰大 G」，因为你很明确地知道自己买不起。可是到了买房，很多人就跟你女朋友一样，觉得「咬咬牙也就买了」，不再去精确计算自己到底能买得起多少钱的房产。

那买房如何才能量力而行，如何计算自己的收入可以负担得起多少钱的房子呢？我们可以参考加拿大联邦政府建议的计算方式，叫做 Gross Debt Service (GDS) ratio 和 Total Debt Service (TDS) ratio [^mortgage-tool]。基于 GDS ratio，加拿大政府建议房屋按揭贷款加上每月生活必须支付的水电费（在加拿大还需要再加上房产税），不能超过税前总收入的 32%。而基于 TDS ratio，则建议按揭贷款、水电费、买车等其他贷款的总和，不能超过税前总收入的 40%。

举例来说，如果你每月的税前收入是三万元，水电费每月两百元，那你每月的按揭贷款不能超过 9400 元。如果按照年利率百分之五、二十五年付清、首付百分之二十五来计算，那你要买的房子不能超过 215 万元，而买车的开销每月不能超过 2400 元。当然，由于加拿大和国内个人所得税的税率不一样，这些计算还可以再进一步调整。

「咬牙」可以，千万要在你能负担的范围内去「咬牙」。其实呢，我倒是觉得「奔驰大 G」这样的豪华车很多人都可以「咬咬牙」去买，最不济就是买辆二手车再少买些其他生活必需品。而买房子一旦超过了 GDS ratio 和 TDS ratio 的上限「咬牙」去买，搞不好会因小失大，为了一点儿「安全感」，小半辈子的日子一直在缺钱的状态中度过，会过得很不开心。

「房奴」有两种：幸福像花儿一样的「房奴」和捉襟见肘狼狈不堪的「房奴」。你希望做哪一种呢？

<div align=right>
2020 年 1 月，多伦多
</div>

[^mortgage-tool]: [Mortgage Qualifier Tool](https://itools-ioutils.fcac-acfc.gc.ca/MQ-HQ/MQCalc-EAPHCalc-eng.aspx), last accessed on August 13, 2020.