---
title: 追星
weight: 19
slug: 幸福/追星
目录:
  - 01幸福
标签:
  - 2019年
---
##### 一

周末参加了的一个学术会议的晚宴。晚宴上群星荟萃，「大佬」云集，舞台上美丽的主持人还在致谢，舞台下觥筹交错，敬酒环节已经提前悄然开场。

「李老师您好。我先干为敬，您随意！您用微信吗？」

「瞧您这话问的 —— 这跟问 “你会说中文吗？” 差不离儿了吧？」

「那我能加一下您的微信吗？」

「没问题没问题，不过我是真的没有朋友圈儿，不是把您屏蔽了啊。」

正当我习惯性地拿出手机打开微信二维码的时候，舞台上忽然传来了亲切熟悉的歌声。我转过头去，看到舞台上一位女歌手，身材高挑，披肩长发，手持麦克风，正在开始唱黑豹的《无地自容》。

##### 二

这种感觉很神奇：在一场规模盛大的晚宴上，在一片嘈杂的敬酒祝辞中，竟然听到了一首二十多年前清华的校园广播中常常播放的摇滚歌曲。歌声高亢浑厚，动人心弦。

它让我想起了我的《幸福》这本书里的同名压轴作品「幸福」中的一小段儿：

> 我二十岁生日那天请客，在大学生之家请哥儿几个大吃大喝。晚上十点多钟，她下自习路过时隔着栏杆看到我们，明显停了几秒钟。大学生之家的大喇叭里，正放着黑豹乐队的《无地自容》：人潮人海中又看到你 / 一样迷人一样美丽 / 慢慢地放松慢慢地抛弃 / 同样仍是并不在意 / 你不必过分多说你自己清楚 / 你我到底想要做些什么 / 不必在乎许多更不必难过 / 终究有一天你会离开我。

节目结束后我问主持人：「能帮我介绍一下儿这位唱歌的老师吗？」

见到这位从未谋面的女歌手的一瞬间，我想起电影「A Star Is Born」里 Lady Gaga 刚刚唱完《Always Remember Us This Way》以后的一段儿台词：「That was unbelievable. That was unbelievable what you did out there.」

##### 三

我们后来简短地聊了一会儿。从当年的窦唯和张楚，聊到 Lady Gaga《I’ll Never Love Again》最后忽然切换到 Bradley Cooper 在钢琴边上唱的尾声：「Don’t want to give my heart away to another stranger...」

她说：「我无数次感叹，如果没有音乐，我的快乐将会少一大半儿。」

聊到《无地自容》和当年的校园广播，她说：「每个人的记忆中都有这样一首歌，这也正是音乐的魅力。」

聊到酣畅之时，我想起了《Always Remember Us This Way》里的歌词：「When the sun goes down, and the band won’t play, I’ll always remember us this way.」

「刚才刚好录了一段您唱这首歌儿时的视频 —— 我能加一下您的微信吗？」我拿出手机说。

<div align=right>
2019 年 5 月，成都
</div>
