---
title: Chill
weight: 17
slug: 幸福/chill
目录:
  - 01幸福
标签:
  - 2019年
---
李老师，祝您青年节愉快。我也来私信求解惑了。是一个关于「原则」的问题。比如，最近和朋友玩游戏喝酒，喝一杯我就是喝一杯，倒满。朋友们喝着喝着就会倒少点儿，最后几乎成半杯了。褚老师引用过一句 GQ 的话，曾对我有所帮助，大意是「在一个俱乐部，两类人比较讨厌，一是没规矩的，二是太坚持规矩的」。所以想问下李老师怎么看。一，我是否应该坚持「满杯」。二，我是否应该坚持自己且不用在意别人的「鸡贼」做法。求指教。（问题来自微博私信）

##### 一

你知道褚老师说的这个「GQ」杂志的名字是哪两个英文单词的缩写吗？

没错儿，是「Gentlemen’s Quarterly」——「男士季刊」。

可是「GQ」杂志其实不是季刊，也不是双月刊，而是一份月刊杂志。

这不是丢人吗？作为一份美国最有名的男性时尚杂志，连名字都在误导读者，还怎么取信于人？

你可能会说，这不是钻牛角尖儿吗？也许这个杂志创刊时是季刊，后来变成了月刊却没有改名，这似乎也没什么关系吧？

去研究 GQ 杂志的名字是否误导确实有点儿钻牛角尖儿。这就好像你第一次去和一个不认识的女生到一家正式的西餐厅约会，发现她竟然先拿那一把靠近盘子的叉子吃开胃沙拉，于是认真地给她介绍了一下西餐刀叉的摆放顺序一样。

大煞风景之余，还完全没有必要 —— 用哪一把叉子吃沙拉，和 GQ 到底是不是季刊一样，是无足轻重的一个细节。

而你所谓的「原则」性问题，竟然是喝酒到底是半杯半杯还是满杯满杯喝的问题。

你所信任的 GQ 杂志还说过，力量训练之后不要喝酒，有氧训练之前也不要喝酒，前一天晚上喝酒还会影响后一天早上运动的成效。总的来说，喝酒无益于健康。

那你是否应该和朋友建议，咱俩要不然别喝酒了，改喝可乐？

等等，可乐也同样含有大量糖分和咖啡因，应该改成喝冰水。如果你朋友的健康不算原则性的问题，那什么是原则性的问题？

你的朋友这时一定会想：这人整个儿傻到家了啊，下次不能再和他喝酒了。

饭局不欢而散，这就是你在「原则」问题上钻牛角尖儿所希望得到的结果吗？

##### 二

前一阵子我在法国开会，碰到了几位学术界的同行，聊到了我的新书《幸福》。我跟他们「宣传」这本书用到的一句名言是：如果搞科研是让你精神紧张的「毒药」，那我的这本书就是让你心情放松的「解药」。

而对于你这样完美主义到了钻牛角尖儿地步的人，我也有一份「解药」—— 美国青少年爱用的一个单词，叫「chill」。

「Chill」这个词儿还真不太容易翻译成中文。从发音来看，让我想起了小时候最爱的「清凉油」；从词义来看呢，又让我想起了一句北京话叫「哪儿凉快哪儿歇着去」。

与其试图翻译成中文，咱要不然还是继续假想那个跟一个未曾谋面的女生第一次约会的故事吧。

第一次约会去一家正式的西餐厅，这个选择本身就明摆着是「chill」的反义词儿 —— 超级「un-chill」。

你想啊，吃完了这么贵的饭你如果说「我来我来」抢着买单，给她一种「欠了你」的心理暗示，她对你的印象能和「chill」沾上边儿嘛。

正确的约会地点是一家路边儿的小饭馆儿，一边儿喝着大扎的啤酒吃着新鲜出炉的烤串一边聊天，既可以半个钟头买单走人谁也不欠谁的，又可以「他乡遇故知」，海聊到馆子打烊。聊着聊着如果正好聊到了她特想去的一家网红甜品店，那不正好是下次一起「chill」的好去处嘛。

吃饭时既不能一句话不说各自玩儿手机，又不能吹上一晚上自己从前光荣的奋斗故事，因为这两者都一点儿也不「chill」。约会结束以后即使再喜欢她也要「chill」，别动不动就给她发微信，让人家觉得你平时无所事事，没有朋友，也无法自己独处。

没错儿，「chill」代表的是一种人生哲学。你越计较的事，越喜欢的人，就越有可能说出钻牛角尖然而却于事无补的昏话，做出南辕北辙的傻事儿来。「船到桥头自然直」，你越不在意，大家的心情就越愉快。

##### 三

当然，如果不是第一次约会，聊天聊到了真正原则性的问题，你一定要就事论事，旗帜鲜明地表达自己的观点。

不过，在清晰地表达你的观点的同时，你还要说明「为什么」：你得出这个结论依据的是什么可靠的论据。

这就像中学时语文课写作文一样：议论文需要明确的论点和论据，逻辑清晰，「晓之以理」；而散文则「动之以情」，形散而神不散。

如果这位和你约会的女生还是固执己见，无法认同你的观点，那说不定你们将来也不太可能互为对方的「解药」，一起过日子也不一定能「幸福」。

最终分手的时候，你如果实在想要完美主义，还是可以找个机会善意地提醒她：西餐里的沙拉，应该是用左手最外面的那把叉子来吃。

<div align=right>
2019 年 5 月，多伦多
</div>
