---
title: 萝卜白菜
weight: 5024
slug: 为祖国健康工作五十年/萝卜白菜
目录:
  - 06为祖国健康工作五十年
标签:
  - 2020年
---
> 李老师好，有个非常纠结的选择需要咨询您。我刚毕业留京，到了很忙的基层当公务员，正在读在职博士。工作以后被离家远的漂泊感、北京的买房等生活压力压迫得忍无可忍，准备取消录用回家乡那边的省会新一线考公或者事业，或者等博士毕业进学校。可是父母反对，他们觉得省会生活压力也不小而且发展弱、考公竞争太大容易直接失业心态更不好。我自己是很不愿意继续在京基层公务员了，因为生活压力太大实在没有幸福感可言，可是父母的观点也很有道理的样子，所以导致我非常犹豫。您能帮忙指点一下么？
>
> 我是独生女也没有对象，自己离家太远这个漂泊感和生活压力太可怕了。而且放眼望去也觉得可改善性很小，本人不是喜欢打拼的性格，希望能过亲朋好友围绕的温馨生活，所以一度想冒险裸辞回去省会重新开始。但是又不确定自己考虑的对不对。
>
> 我最近几天也在反省自己。可能是刚出校园，独立应对生活的能力还不够，一个人没有援助力所以受不了压力了。而且因为我身处基层，单位平台低人员素质低，直接领导是个人品和作风很差的军转中年油腻男，天天被当成情绪垃圾桶和新兵蛋子挖坑欺负，工作特别忙还总受气，痛苦又没价值的工作，一个独生女远离家的孤独，还有未来的压力和恐惧。一来我就在各方面遇到加难题型，我真的都怕自己转正进入服务期走不掉就抑郁了。可是另一方面又觉得自己是不是在逃避压力，去了省会只是房价和家远的压力稍微缓解，还得面临可能短时间找不到满意工作的综合压力，找到了是不是又是另外一个坑。我真的挺纠结，又患得患失的。
>
> 这段时间思考去留的问题，让我精疲力竭十分痛苦，还请李老师指点一二。谢谢老师！（问题来自微博私信）

##### 一

我们先来做一个假设：工作无论做什么，都会有其难处，世上不可能有十全十美的工作。

你不觉得吗 —— 有的工作挣钱多但是太忙，有的虽然闲但是挣钱又太少；有的岗位受别人排挤，有的又责任重大，风险太高；有「痛苦又毫无价值」但是却四平八稳不容易丢的工作，就自然有挺有责任感但随时会失业的工作。

如果我们的假设成立，那你现在的工作虽然离完美有一段距离，可你将来回到省会城市重新找到的工作，很可能比现在也好不了多少。

如果不考虑工作好坏这个问题，那我们的这道选择题就简单多了：如果咱今后打算工作三十年，是住在北京呢，还是住在省会城市？

回答这个问题，我绝对不是一个合格的人选：我北京出生北京长大，肯定带有北京人的偏见。

我的答案是：我不但会选择住在北京，还会找机会到世界上其他的著名大城市都住上一阵子 —— 比方说上海、香港、首尔、东京、纽约、还有伦敦。

也许正是因为我选择的是北京，将来才会有更多的机会去更多的地方。

##### 二

我有一位教授同事，曾经成功创立过一家外汇交易的公司。因为这家公司创立至今发展得非常成功，他早已衣食无忧 —— 按照现在时髦的词汇，叫「财务自由」了。特斯拉刚刚推出 Model S 的那一年，他就买了一辆来玩儿。他戴的智能手表是当年大名鼎鼎的 Pebble，论资历，苹果手表得管它叫「爷爷」。

一次闲聊时，这位同事说起他每个周末把自家的豪华特斯拉开出来，在 Uber 上接单。我觉得很神奇：他也不缺这点儿外快啊，为什么要临时开出租？

他说：就是为了好玩儿啊。

就跟他多年前买了点儿比特币，无论涨啊跌啊从来没卖过 —— 也是为了好玩儿。

工作二三十年，退休了还有二三十年，这么长的时间，我觉得「好玩儿」特别重要。

事业成功家庭和睦自然很重要，但「好玩儿」其实也是一种挺重要的体验，因为还有很多其他可以「玩儿」的。比如周末没事儿去开开出租，是一种「玩儿」法；在单位跟领导斗智斗勇，是一种「玩儿」法；认识一大帮子新朋友一起撸串喝酒侃大山，也是一种「玩儿」法。

而北京这样的大城市，玩儿法多半儿会比回到省会城市多一些。玩儿法一多，日子就变得更加有滋有味。

就像计算机科学里有一种叫「图灵测验」的概念一样，我一直笃信一种测验，我管它叫做「deathbed test」—— 这里的「deathbed」可以说是一个中性词，没有伤感的含义。虽然意思猜都猜出来了，还真没有对应的中文词。

这个测验是在问，临终前对自己玩儿过的这几十年，是像酒足饭饱的那种心满意足的感觉，还是后悔莫及？

我想，如果既跟领导缠斗过，又跟朋友快活过；既开过出租、又当过房奴；玩儿过文艺，弹过吉他，又飙过跑车，到「deathbed test」的那一刻，就不太容易后悔了吧？

否则，如果换了我，我总是会好奇：如果当年选择留在北京住下去，后来会是什么样？

##### 三

当然了，「萝卜白菜，各有所爱」，很多人就跟我截然不同，更喜欢小一些的城镇。这就好像既有喜欢儿孙满堂、也有喜欢丁克的人一样。

我今天读到了一则在环球邮报网站上的留言，说一个加拿大人自己一个人住在阿尔伯塔省的一个小镇附近自己的农场里，离他最近的一户人家在一公里开外，每天只有一条狗陪伴着他。他只需每一两周到小镇上买一点儿水果，其他的吃的喝的农场里都有大量储备。他每天上网逛逛，在家做做木工，日子过得也挺充实。最近的世事纷争和他没什么关系，唯一的影响是小镇上给他安排的义工取消了。

也许是因为我当年是个城里长大的孩子 —— 就算把这个农场送给我，木工玩儿腻了的时候，我也注定会感到孤单。

如果真有世界末日的那一天，我想我会去上海徐家汇或者纽约曼哈顿找一家小酒吧，安静地等待它的到来。

<div align=right>
2020 年 3 月，多伦多
</div>

