---
title: 卷
weight: 5039
slug: 为祖国健康工作五十年/卷
目录:
  - 06为祖国健康工作五十年
标签:
  - 2025年
---

今天朋友给我发过来一篇王朔的专访，其中有一句话印象颇为深刻：人生的归宿是在墙角刷抖音。

换句话说就是，终于不用再「卷」了。

连王朔都刷抖音了 —— 想起八十年代他的处女作《空中小姐》中的那份张狂、那份柔情，不禁有一种「the end of an era」的伤感。

「卷」这个词儿挺新的。大概比「颜值」还晚几年才出来，可一出来就红遍了大江南北。比如说吧，前一阵子端午节我初次访问南京大学，和好几个新老朋友吃饭聊天，听到最多的词儿就是「卷」。

也许是我一厢情愿吧 —— 我愿意相信，「卷」有时也是个褒义词。

为期一周的访问一晃而过。在校园里骑车、在食堂吃饭、在办公室写代码之余，印象尤为深刻的是有幸结识了几位计算机专业的青年学者，个个著作等身、思路清晰、看问题的视角独特，令人眼前一亮。按照现在流行的说法，都是什么什么「神」。长江后浪推前浪，青出于蓝而胜于蓝 —— 确实太「卷」了。

当然了，江苏省人杰地灵，南京大学又是全国少有的顶级高校之一，这里青年学者的学术水平高，那也是意料之中的事儿。但他们的「卷」，还不仅仅体现在善于发表论文方面，更体现在其演讲、提问、和交流的能力，体现在对人工智能和物联网等新技术发展趋势的细致观察。说来也巧，这里的国家实验室就叫做「软件新技术」，有的教授主持着工业界广泛应用的云计算开源社区，有的则发明了简单到一听就懂、又复杂到需要好几年时间积累而得的巧思奇想，「卷」到了令人匪夷所思的地步。

有趣的是，南京还有一个科举博物馆。我忙里偷闲去参观，发现当代之「卷」和古人之「卷」比起来，完全不可同日而语 —— 古人穿越时空到如今，是绝对的「卷王」。博物馆中收藏了不少当时科举考试中考生的试卷，在八股文的条条框框中照样文采飞扬，蝇头小楷则美不胜收，简直就是文学和艺术集于一体的巅峰之作啊。

遥想几十年前的王朔，那也自然是意气风发，大街小巷的书摊上，随处可见他的文集。「五十步笑百步造句 —— 前五十步笑，百步以后哭」，幽默而不失深意。他当年的「卷」，卷成了家喻户晓的风云人物，卷出了可以传世的作品，卷到了在墙角刷抖音都能刷到自己的时候，人生真的无憾了吧。

南京的一次接风席间，一位青年学者，熟读历朝历代诗词绝句，西瓜汁过了三巡，他站起身来，说：「今天没喝酒，本来当场不一定会有灵感，但是既然恰逢端午，李老师又远道而来，我吟诗一首给大家助兴如何？

> 端午黉门迎李公
>
> 南雍端阳驻鸿儒，<br>
> 菰叶葆香润春珠。<br>
> 千舟竞发深求索，<br>
> 犹记沧浪清与浊。」

「卷」到如此境界的人生，也是一种可遇而不可求的幸福。

<div align=right>
2025 年 6 月，多伦多
</div>
