---
title: 迷茫
weight: 5041
slug: 为祖国健康工作五十年/迷茫
目录:
  - 06为祖国健康工作五十年
标签:
  - 2025年
---

> 李老师好，您是我非常崇敬的老师，同时我也是您的笔迷。我刚刚博士毕业，现在的状态总结为可用「迷茫」来概括，若老师有空，是否能指点迷津，不胜感激。
>
> 我的家境一般甚至偏下，有两三篇还算拿得出手的论文成果。老师们说我年龄大了，应该找个有钱人结婚生子解决经济问题。也说我应该去海外博后，拿了海优再回国。我在毕业前夕找了互联网薪资还算不错的工作，后来觉得还是想做教职，就退掉了。但其实海优其实难度较大，不一定能申请得上，而且近些年毕业的博士越来越多，在海外呆几年再回国，可能现在有的 offer 也找不到了。
>
> 而且本来做科研就是件辛苦的事，我有时看到学术圈里的人搞圈子，真的觉得心灰意冷。我不知道应该早早去上班赚钱，还是继续在染缸里坚持下去，做博后做科研找教职，又或者是早点退出这里放弃理想结婚生子赡养父母... 对不起老师，可能我的观察过于片面，思考也有偏见，如果老师有空，能否讲讲您的看法？我将受益终生。（问题来自微博私信）

##### 一

很多时候，做一个关键的决策，都像是在解决一个优化问题。

简单起见，咱这个优化问题只有一个优化目标，而把其他所有目标都转化为约束条件。

比如，你的问题中，是希望既能收入越多越好，又能有一份和自己的兴趣爱好相近的稳定工作，还能找到称心如意的伴侣结婚生孩子。而你的选择有三种：去工业界工作，去学术界工作，或者找一个优秀的 —— 最好是有钱的 —— 对象结婚。

这里首先有一个问题。最后一个选择，和你前两个选择其实并不矛盾。理论上来说，找对象结婚需要花一些时间，但是即使想找特别优秀或者特别有钱的，也不太可能需要全职。既然如此，咱们可以假设，你的选择有两种：

是去工业界还是去学术界工作？

##### 二

如果我们根据第一性原理摒除一些海优啊圈子啊关系不大的细节，两者之间的区别在于：工业界工作收入高不少，但是不太稳定，工作本身你可能不太感兴趣。学术界工作呢，收入虽然低，但是相对稳定一些，工作本身也更有可能和自己的兴趣爱好相近。

我们粗线条地大致分析一下：如果你的优化目标很明确地定义为最大化收入，那似乎工业界是首选。而如果你的优化目标是兴趣和学术理想，学术界则成为首选。

当然，这个优化问题的分析还需要加一两个脚注。如果咱们假设学术界你可以顺利拿到编制或终身教职，可以工作三十年。而工业界风险甚高，十年后就会丢了工作。那工业界的税后工资需要是学术界的三倍或以上，才会在优化收入时首选工业界。同理，如果学术界也有因为「非升即走」而「走」的风险，而这个风险还不小，那可能工业界工资只需要是学术界的两倍左右，就可以首选工业界。

所以，咱们化繁为简，如果你想将收入最大化，这个优化问题的答案，完全可以靠计算工业界和学术界每年收入的比例得出。比如，如果某一所大学给了你每年税后收入四十万元的 offer，等同于工业界给你每年八十万元的税后总收入。而如果你更想实现自己的学术理想和满足自己对学术的兴趣爱好，同时又对学术界的圈子感到失望，那你可以琢磨一下自己到底对理想有多追求，对圈子的现实有多失望，适当提高或者降低以上比例来选择。

##### 三

那你对「卷」帽子啊「混」圈子啊等等到底应该有多心寒呢？

你要是去刷知乎小红书，那估计得出的结论是应该透心凉才对。

但是这里有一个问题：只要有人的地方，就会有「帽子」和「圈子」。不仅仅是学术界，工业界自然也一样。所以，如果你对两者都嫉恶如仇，只希望肝胆相照地做一些实事儿，那要是你正好读到你想去的公司的若干「内情」，大概率一样会心寒。因为这么伟大的、能敞开极其有限的资源让你在知识的海洋中自由驰骋的公司，估计凤毛麟角。

既然到处都是各种形形色色的「帽子」和「圈子」，那你为什么就不能也去这些「染缸」中闯荡一下江湖？

万一 —— 我说的是万一哈 —— 二三十年以后，你也能或多或少地在这样的「圈子」中，以自己本色出演而鹤立鸡群，以出众的才华、过硬的技术、雄辩之口才而立于不败之地呢？

##### 四

人生的意义是什么？

我一直觉得，人这一辈子，就像在苏州园林中缓缓倘佯，有一种「移步换景」的效应。喜事儿当然是换景：高考考上了，换了一景，论文高中了，换了一景；工作顺利找到了，又换了一景。失望伤心的事儿其实更是换景：失恋了，换了一景；论文屡投不中，换了一景；公司裁员了，则又换了一景。

人一辈子的意义，也许就在这一惊一诧之间，淋漓极致地体现了出来。

而什么才是成功？

我有一个「悼词」的理论：一个人成功的标志在于，他（她）百年之后，有一个熟悉他的人，专门花了一天时间，给他写了一篇洋洋万言的悼词。这篇悼词记录了他一生的跌宕起伏、起承转合。这里有他的理想，也有他的「圈子」，但更多的是他的喜怒哀乐，他的待人之诚，他举重若轻的幽默，还有他令人刮目相看的才华。

也许我们选择需要优化的目标，应该既不是收入、也不是理想，而是如此这般定义的「成功」吧。

<div align=right>
2025 年 7 月，多伦多
</div>
