---
title: Hit and Roll
weight: 7033
slug: 柴米油盐酱醋茶/hit-and-roll
目录:
  - 08柴米油盐酱醋茶
标签:
  - 2023年
---
冰壶常规赛季结束了，我们队排名第二。昨天季后淘汰赛（Playoff）开始，我打二垒，第一场对阵排名第三的队。

冰壶运动一场分为八局，四个人一队，一垒（lead）和二垒（second）不如三垒（vice）和四垒（skip）重要，后者可以随时扭转乾坤，左右胜负。

第六局打完，不但比分二比五落后，对方还拥有最后掷球权。英文把最后掷球权形象地称为「锤子」，颇有一锤定音之意。若是能从「锤子」手里得分，英文叫做「您就偷着乐吧」（steal）。

我们队超常发挥，竟然「偷着乐」了两局，第八局打完，追成五比五平。

这可是新鲜事儿。我打了五年冰壶，从来没有过淘汰赛平局需要加赛的经历。

至关重要的第九局，开场对方三个冰壶在营垒（house）里面，形势极其不利。我们 skip 叫 Joel，属于想赢怕输的性格，离得老远都能看到，他的脸色已经很难看了。

我打第四个冰壶之前，Joel 用冰刷比划了一下，用意是让我「hit and roll」—— 把对方冰壶打出去的同时，自己的冰壶侧滑一小段，躲在对方其他冰壶的后方。

冰壶两大要素是「line」和「weight control」。「line」是要不偏不倚地对准，而「weight control」则是力道要合适，冰壶速度不快不慢。这个「hit and roll」要把对方冰壶打出去，所以不能太轻；自己又要侧滑一小段，所以又不能太重。

近一年来我冰壶水平有很大进步，竟然在关键时刻打出了一个完美的「hit and roll」：把对方的冰壶打出去以后，自己的冰壶 —— 英文形象地叫做「shooter」—— 竟然真的缓缓侧滑了一小段，停在了「house」的中心。

最后我们队因为我这一个冰壶险胜。

看到 Joel 喜笑颜开的样子，我想起了五年前刚认识他的时候，他还不在我所在的队。当时比赛结束大家一起喝酒，Joel 听说我要去香港访问，也是像此时此刻这样的神情，眉飞色舞地跟我吹：「你知道吗？香港有一家馆子叫 Mott 32，就在汇丰银行总部的楼下，他家的烤鸭惊艳无比，真的是一绝！」

我当时差点儿跟他说：「你知道吗？我是一个北京人。」

<div align=right>
2023 年 4 月，多伦多
</div>
