---
title: 细节
weight: 7035
slug: 柴米油盐酱醋茶/细节
目录:
  - 08柴米油盐酱醋茶
标签:
  - 2024年
---
我发现这个微信群有一个好处：有些和产品相关的想法，我不太敢发在微博 —— 怕人说是「带货」—— 但是正好可以在群里讨论。

这个关于「带货」的执念也挺神奇的。无论你说点儿什么， 但凡是跟某产品有关，就一定有人觉得你是「充了值」，是「带货」，不知道是不是因为不「充值」不「带货」的人现在已经绝迹了。

有一个很小的细节，我一直在琢磨着，琢磨了很多年。

这就是如何建立和使用一个「To Do List」—— 中文还真搞不清如何翻译 —— 「待办事务清单」？

To Do List 的特点，是一共只有两个动作：加入一个新的 To Do，和打勾完成一个已有的 To Do。加入新的 To Do 时，可能会有一个需要完成的日期。无论是什么 app，都应该支持显示现在需要完成的事项。这两个动作需要同时可以在手机或电脑上完成，To Do List 两者需要完美同步。

关键的问题在于，这两个动作，都必须非常容易完成，否则我时间长了坚持不下去。可全靠脑子记也不是一个办法，因为不可避免的会忘掉一些重要的事情。

以前曾经试用过很多 app，都感觉不是很好用。有的 app 太复杂 —— 但凡需要学习怎么用的 app 都太复杂 —— 而有些 app 呢，比如一个名叫「Clear」的 app，则又太简单，To Do List 太长时，无法只显示马上要做的工作，也无法和电脑同步。最重要的问题是，绝大多数 apps —— 比如 iOS 自带的 Reminders —— 输入一个需要完成的日期太麻烦，需要在手机或电脑上进行好几步操作。

最近终于找到了我觉得比较完美的 To Do List，是用一个万能的叫做「Obsidian」的 super app 实现的。Obsidian 本身免费，但是和电脑同步需要一小笔订阅费。用 Obsidian 输入 To Do List 的好处是非常简单，它支持 Markdown 格式，只需要输入 「- [] Proposal reviews due @due (2024-03-22)」一行字，几秒钟就可以同时记录待办事项和需要完成的日期。Obsidian 里有一个叫做 Cardboard 插件，可以完成打勾的动作，自动记录完成时间，并可以显示今天需要完成的事项。

Obsidian 还有很多其他功能和优点，我有机会以后再慢慢「带货」。但是这个关于 To Do List 多年悬而未决的难题，竟然就这么轻而易举地解决了。有了这么一个普通但是很好用的 To Do List，我完成工作的效率有明显的提高。平常不怕忘记了什么重要的工作，也不如以前那么焦虑了。

这篇文字，也是在 Obsidian 中写成的。它自动同步到我的手机，还可以在发出之前简单修改一下，堪称完美。

<div align=right>
2024 年 3 月，多伦多
</div>
