---
title: 离婚
weight: 1028
slug: 将爱情进行到底/离婚
目录:
  - 02将爱情进行到底
标签:
  - 2019年
---
> 李教授你好，看了很多你的微博文章，觉得你都能从平凡生活中体会到人间喜乐。最近婚姻生活遭遇严重打击，夫妻缘分耗尽在最后一刻，签了分居协议，关于小孩的抚养以及为数不多的财产的处置。在我看来即使是分手也希望好聚好散，不知道如何去劝慰孩子爸爸。孩子父亲是统计学 PhD，性格上比较固执也不善交谈。无法接受他的条件，就是不想分手但是也不想让你好过，无法心平气和。如何去面对这样一个尴尬的过程，希望你能给一些建议。（问题来自微博私信）

##### 一

「好聚好散」看起来挺简单，但实际上是很难做成的一件事儿。

难就难在你觉得这么「散」是「好散」，他却觉得那么「散」是「好散」。你们俩如果分别到我这个「街道居委会」来哭诉，我一定会觉得你说得确实很在理儿，他也确实有他的难处。

比如说吧，你多半儿会拿「孩子的抚养」说事儿，抱怨他再怎么着总得多想想孩子吧？而他想着的则可能是你们俩多年的感情，说结婚这么多年了，总不能无情无义到了直接扫地出门的地步吧？

而「街道居委会」作为观众，「是非曲直未有所定」，立场也很难说向着谁。就好像三五好友一起看多年前的那部《中国式离婚》，「吃瓜群众」有的同情陈道明演的宋建平，有的却反过来去支持蒋雯丽演的林小枫：「谁叫宋建平没事儿就跟娟子眉来眼去的？」

俗话说「当局者迷，旁观者清」，现在连旁观者都有的「站」「李总」，有的「撑」「俞总」，长篇大论连篇累牍地先掐起来了，当局者还怎么能「好散」呢？

所以依我看啊，你们夫妻俩结婚时间越长曾经的感情越深，「好聚好散」就越没有希望。

能「散」就已经不错了。

##### 二

我外公在六十多年前写的《龙虫并雕斋琐语》中，曾写过一篇短文，叫《夫妇之间》，正好就提及了夫妻打架 —— 现在时髦的语言叫「开撕」—— 的问题。他在文中写道：「夫妇反目，也是难免的事情。但是，老爷撅嘴三秒钟，太太揉一会儿眼睛，实在值不得记入起居注。甚至老爷把太太打得遍体鳞伤，太太把老爷拧得周身青紫，有时候却是增进感情的要素，而劝解的人未必不是傻瓜。」

你瞧，其实夫妻打架也不完全是一件不幸的事。即使不能增进感情，至少也给自己积攒了一点儿阅历，给日子增添了一点儿颜色。将来老了动不了的时候，大概和丈夫当年的相见恨晚含情脉脉早已忘了一干二净，却竟然还记得「缘分耗尽」的那些最后一刻，然后不忘了再为「男的都不是好东西」这样的永恒真理叹一口气。

外公的文字笔锋一转，还写了另外一种离婚：「倒反是有些相敬如宾的摩登夫妇，度了蜜月不久，突然设宴话别，揽臂去找律师，登离婚广告，同时还相约常常通信，永不相忘。」乍一看来，这种摩登的离婚方式堪称完美；但是再一琢磨，你大概会觉得这种「好聚好散」的离婚既不打架又不「开撕」，如同白开水煮挂面一般，缺少了「中国式离婚」的精彩回合，还略微有那么点儿遗憾不是？

所以说啊，能好好聊聊好好劝当然很好，否则大大的打上一架，歇斯底里，快意恩仇，哭得昏天黑地，岂不也是一番不同的人生体验？

虽然将来不太会经常通信，但一定会永不相忘。

##### 三

什么事儿都有好坏两面 —— 离婚的好处，是从唯一选择回复到无穷多的可能性，就像手机恢复了出厂设置，新生活从此开始。

再次体验一把到麦当劳跟陌生网友相亲的过程，今天跟这个见见，明天再跟那个聊聊，喜欢就穷追猛打，不喜欢就微信拉黑，「滚滚长江东逝水，浪花淘尽英雄」，多来劲儿啊。

离婚有点儿像从现在的公司辞职，就算还没找好下一个工作，也不能算是「失业」，而只不过是暂时「in between jobs」而已。

就是下次再结婚，别忘了签一份婚前协议。

<div align=right>
2019 年 10 月，多伦多
</div>
