---
title: 跟着感觉走
weight: 5023
slug: 为祖国健康工作五十年/跟着感觉走
目录:
  - 06为祖国健康工作五十年
标签:
  - 2020年
---
> 李老师，好久没看您发微博啦。最近看一个剧里有句台词触动很大：人生一世，选条路，不退让，不更改，一直走下去，是件幸事。我感觉，随着认知面的拓宽，自己越来越会辩证地去思考问题，且随着知识情感等不断地丰富，这个辩证的过程也会变得越发的复杂甚至最终被困于其中。就好像我有两个我在打一场少有结局的辩论赛。所以有些时候看到一些「一根筋」的人，会羡慕他们的单纯可爱并为其事迹感动。所以，是不是我「想太多」呢？又怎么让自己不想太多呢？（问题来自微博私信）

想得多一点儿，其实是好事儿啊。如果「一根筋」的结果是「一条道走到黑」，而非「浪子回头金不换」，其实也不是什么特别让人羡慕的事儿。

当然了，咱也不能想得太多 —— 天天想，月月想，想过来再想回去，结果没真正做成什么事儿，自然也不可取。

尽量在两个极端中找到一个「sweet spot」—— 中文直译过来我觉得可以叫 「甜点」—— 想得不能太多以致一事无成，也不能太少以免「一招不慎，满盘皆输」。

那这个「甜点」在哪儿呢？

我个人认为，可以沿用类似法律体系中的那套路子，给自己确立几条「公理」—— 有点像法律体系中的宪法 —— 只要不违背这些「公理」，其余的不用想太多，「跟着感觉走」就可以了。

那这些「公理」都是什么呢？

我今天就抛砖引玉，说两个例子给你参考吧。

##### 一

第一条「公理」是：不要人云亦云，要货比三家。

我考大学的那会儿，很多人都认为学生物工程是最好的专业选择。因为当时离二十一世纪还很遥远，人工智能还处于寒冬，大家都觉得等中国人民的生活实现了小康、国家实现了四个现代化之后，生物工程是未来的发展方向。结果很多当年最杰出的人才都去学了生物，后来去了美国留学，读完博士发现找不到工作，只好继续读博士后。读了博士后还找不到工作，只能转行学计算机，因为学计算机好找工作。

时间过得很快，现在「三十年河东，三十年河西」，很多人都认为应该去学计算机，甚至再细分一点儿去学人工智能，量子计算，或者区块链。可是，现在热门的专业，不等同于十年学成以后还热门啊。

这条「公理」就派上了用场：不要人云亦云，要货比三家。

可是怎样才能做到「货比三家」呢？

我的建议是，不能只听信一些「专家」、「大神」的意见，更不能直接相信满屏的公众号文章，而是正反双方立场各找出一两条高质量的意见，仔细研读一下，然后再通过独立分析得出自己的结论。

选读别人的意见时，还要考虑到作者是否有利益相关。比如一位研究人工智能的学者，多半儿会说一些有利于人工智能研究的观点。我们可以了解他的观点，但是也要观察其观点是否有失公允。

「货比三家」说得是，参考两三种不同意见就可以当机立断地拍板了，不需要太多。选好了就开始执行下去，就算后来发现选错了，也已经尽力而为，不用后悔。

##### 二

第二条「公理」是：生活第一，工作第二，做一天和尚撞一天钟。

每个人的时间都是有限的资源，需要在工作和生活之间分配。很多人喜欢把自己的工作放在第一位，生活放在工作之后。我的这条「公理」是说，生活才永远是应该第一位的，工作远远没有我们想象的那么重要。

你想象一下，如果知道很快就要离开这个世界，今天晚上躺在床上会想些什么？

我也许会想我的家人，我的孩子，我的宝贝汽车和音响，甚至我的梦中情人。

但我想我一定不会去想我的公司，我的单位，我的论文，和我得到过的荣誉。

大多数幸福和快乐，都来自于「业余时间」的生活，而非工作。比如我现在给你写这篇回答，是我生活的一部分：高兴了就写点儿，没什么可写的就懒上一阵子 —— 这也是为什么我可以很长时间不发微博的原因 —— 写完了有人喜欢看有人点赞，让人心情愉快。但是如果让我把写公众号文章当做工作来做，每天一定要完成多少写作的工作量，我想我一定不会喜欢，幸福感会大打折扣。

所以我觉得，在分配自己的时间和做各种取舍选择时，应该永远把生活放在第一位，因为生活才是幸福的源泉。工作可以认真地「做一天和尚撞一天钟」，一切顺风顺水自然很好，如果正好不尽如意，那就听天由命好了。

想起了我在美国第一位导师 Dan Reed 的一句名言：

>Too many good books, and too little time.

##### 三

只要把这几条「公理」记住，余下的就交给运气和时间吧。

别人如果「一条道走到黑」，不一定是一件「幸事」，咱们也不必羡慕他们，也不必为他们的事迹而感动。

咱就一普通人，踏踏实实地过着一普通人的日子罢了。只要自己开心，既可以「从一而终」，也可以「朝令夕改」。

生活就像一艘帆船 —— 咱们要想要做的，是如何把帆迎着海风展开，让它鼓得高高的，全速前进。

<div align=right>
2020 年 1 月，多伦多
</div>
