---
title: 好酒不怕巷子深
weight: 7028
slug: 柴米油盐酱醋茶/好酒不怕巷子深
目录:
  - 08柴米油盐酱醋茶
标签:
  - 2020年
---

> 李葆春老师中午好。在电子诈骗中被骗的人，无论是出于贪还是侥幸的心理，您对这样的人、对被骗这种事怎么看？
>
> 撇开不讨论电子诈骗以及其他金钱骗局的低端、低技术含量和明显的诈骗性，也不谈普通人要有防诈骗的警惕心、不要明知故犯或贪心、要培养脚踏实地的性格或者政府应该积极打击诈骗犯，只谈那些不幸被骗的人，是不是被骗本身说明这类人确实人生的路会更难？
>
> 一辈子有可能不被骗吗？被骗过后会不再上当吗？人生又是否又会有重来的机会呢？为什么人性这么脆弱？（问题来自微博私信）

##### 一

七年前有一个夏天，我正好在西安出差，准备在当当网上邮购一些书带回加拿大。我用我当时的手机号码注册了一个账号，选好了几本书，就下单了。虽然那时我没怎么在国内网站上买过东西 —— 即使到现在我都没有淘宝的账号 —— 但我一直听说国内的电商极其发达，只需要一两天时间，书就可以轻松地快递上门。

第二天，我接到当当网的客服打来的电话。客服首先跟我核对了一遍我的订单号、名字和快递收货的地址，然后客气地说：「李先生，不好意思，您的快递暂时缺货，需要先给您操作退款，等有货了再给您重新下单。」

我回答：「行，那你就先退款吧。」

「先生，您有没有 QQ？」

「对不起，我没有 QQ。你要 QQ 干嘛？」

「哦，是这样的先生，咱们这里查到您是用网银支付的，操作退款需要把钱原路退回给您的银行账号，需要您提供一些信息，所以必须用 QQ 联系您。」

「我确实没有 QQ。你要什么信息？」

「那实在不行要不然这样：我这里有个网站，给您短信发过去了，您登录填写一下您的信息，填好了告诉我，我在线等您。」

网站我一下就打开了，里面提示我填写银行账号、收款人和密码。

后来我回想起来，真的是有点儿悬。直到打开这个网站之前，我还没有意识到这其实是个骗局。主要原因是对方刚开始就报出了我的订单号、收件人姓名和详细地址，骗取了我的信任。但是这个骗局的设计稍微有些粗线条，有两个明显的破绽：第一是对方带有南方口音的普通话，第二是让我填写账号密码。

对了，还有他后来愈发焦急的催促：「您填好了没有？填好了没有？」

电信诈骗之所以这么多年来一直没有杜绝，非常符合经济学的原理。由于作案风险相对比较低，获利又相对比较高，就会有更多的人投入其中，组织和分工也会越来越精准严密。再加上其套路层出不穷，年年都可以推陈出新，令人防不胜防。

所以我对在电信诈骗案中被骗的人非常同情 —— 我自己研究了半辈子计算机，也没有什么贪小便宜的心理，又历来小心谨慎，当年都照样差点儿上当。

##### 二

那将来会不会再次上当受骗呢？

这得看你这个「受骗」如何定义了。

如果只是电信诈骗中的骗局，我想大多数人多半儿可以「吃一堑长一智」，不接陌生人的电话，基本可以对这种骗局「免疫」。

但如果你把什么「P2P 理财」啊、「币圈儿」啊、「直销」啊、「万能保险」啊、「投行权威分析」啊什么的全都算上，那很可能你今后还会再「受骗」，而且还不止一次。

这是因为在如今的信息时代，每天主动读到和被动接受的信息和观点实在太多，哪些是正确的，哪些是错误的，哪些是事实真相，哪些则是以假乱真的宣传，不太可能有一种万灵的方法，可以保证自己的判断每次都准确无误。

不过你大可放心，这样的「受骗」就如同一家企业在市场中的亏损一样，并不一定是一件坏事儿。盈利是一种市场信号，亏损也是一种信号。和盈利比起来，亏损甚至可以让一家企业更有效地重新优化整合自己的资源配置和产品策略，积累更宝贵的经验。

一个人更是如此：赚钱的时候春风得意，而一旦因为判断失误听信了别人的「权威分析」上了当亏了钱，「痛定思痛」，总结出来的经验只会更加宝贵。

所以说啊，人生完全不用「重新开始」，以后的好日子还长着呢。

##### 三

不过道理虽然这么说，要是换做是我，总还是会希望尽量多「盈利」少「亏损」，少总结宝贵的失败经验，心情会好很多。

我有三条「锦囊妙计」，说不定可以派上用场。

第一条是尽量不要人云亦云，盲目「跟风」。比如，如果大家都去买比特币或某种高回报的理财产品，你则要冷静下来持怀疑态度，问一个关键的问题：买房也好，比特币也好，P2P 理财也好，这种投资为什么可以盈利？风险多大？风险从何而来？如果经过冷静的独立思考，觉得对这些问题的回答逻辑严密、符合常理，再去跟风不迟。

第二条是多考虑长期的影响，少考虑短期的效益。经济学家 Thomas Sowell 管只看短期效益的短视行为叫做「Stage One Thinking」。Sowell 指出，很多决策的制订都仅仅看到了短期的好处，没有考虑长远的负面影响。比如，如果有这么一种理财产品，头一年的回报百分之十，但长期来看没有保证，我们就一定要估算一下其长期的风险，连为其担保的公司倒闭的风险也要计算在内。

最后一条是尽量避免「冲动消费」。商场或网站大减价的或者「直播带货」的产品，都属于别人给你推销的产品。这些绝大多数都不是你需要的产品，很可能完全不适合你。但是你因为一时兴起，说不定就下单买下了。买了以后没怎么用，就造成了有限资源的浪费。而「好酒不怕巷子深」，质量上乘、做工精细的产品，你排队抢购都不一定抢得到，不会天天大减价推销给你。

比如说吧，如果我现在告诉你，我准备近期隆重推出一个名为「好酒不怕巷子深」的私人朋友圈，为期四周，每周两小时。届时将汇集我的三位老朋友作为嘉宾，有你早已耳熟能详的「大 V」，有学识渊博的学者，还有神龙见首不见尾的高人，没有什么主题，大家根据共同关心的话题，全程语音互动，想聊哪儿就聊哪儿。由于平台资源限制，名额有限，优惠价格在评论里找，请大家尽快报名。

你可千万不要参加。

<div align=right>
2020 年 6 月，香港
</div>

