---
title: 理想国
weight: 24
slug: 幸福/理想国
目录:
  - 01幸福
标签:
  - 2020年
---
葆春老师好。经常看您的微博，您的回复真诚实在，给即将毕业步入社会的我很多启发。我原本打算留学美国，托福 GRE 也已经考完，现在虽然拜登赢面大，但是现在考虑到特朗普期间急转直下的中美关系，美国大幅取消中国留学生签证，心里还是打鼓。想请教下您怎么看待 2021 年留学美国的形势呢，是不是现在对于留学生而言，放弃美国考虑其他国家才是明智之举。非常感谢您！（问题来自微博私信）

##### 一

中美关系我虽然不懂，但是我以前提起过我的舅舅王缉思，他研究中美关系数十载，是国内当之无愧的中美问题专家。所以但凡跟中美关系有关的问题，我都去读他的文章，希望从中找到答案。

他十年前曾经写过一篇文章，题目是《如何看待美国地位的相对下降》，后来也经常重申其中的观点：和其鼎盛时期相比，美国虽然有衰落的迹象，但是「瘦死的骆驼比马大」，对于我们这些普通人，离真正需要担心是否要去美国留学这样的问题的时候还很遥远。我们还是来摘抄一段王缉思教授的原文吧：

「我们的问题在于下结论太草率，往往凭一时一事。如九一一事件发生，有人认为美国从此就不行了。现在利比亚的危机出现，美国束手无策，于是乎美国不行了。对于金融危机的判断也是这样。关于美国兴衰的研究，我想有许多问题可以讨论，但我这里想说的是，国内的研究者也好，我们的整个舆论也好，几十年来低估美国、唱衰美国的时间更多一些，而有很多次已经被事实证明是错误的。有的时候就是一种情绪被掺杂在研究或者判断里面：我不喜欢美国，就不喜欢说美国强大。」

同样的道理，现在虽然财政危机、政治两极化等问题还在更为集中地不断出现，但是如果我们把眼光放长远一点儿，很难就此认定美国已经从此衰落、一蹶不振了。既然如此，如果我们假设美国的学术水平无论人文还是工程学科还是世界一流的，那我们就没有任何理由不去这样全世界最好的一流大学留学。这些大学有最好的师资力量和科研实力，留学又是「过了这村儿就没这店」的事儿，为什么要舍本逐末呢？

我听说，很多国内的学生都考虑放弃去美国，而改为去其他国家和地区的大学留学。如果这是因为客观的因素比如疫情或者签证问题，当然无可厚非；如果是因为「急转直下的中美关系」而自己改了主意，那我就不明白了：中美关系跟我们普通人去美国留学有什么本质或必然的联系？不仅如此，我这个人还天生有一种「逆水行舟」（contrarian）式的叛逆心态：如果大家都因为微信公众号看多了而不去美国留学，不正好是我去美国最好的机会么？

我盲目地相信，那些号称不去美国的同学，如果收到一份哈佛法学院的录取通知书，一样会兴奋地跳起来。他们不去美国，多半儿不过是嫌自己申请到的学校不够知名而已。

##### 二

不过，不知道你发现没有，很多人但凡选择了在一个国家或地区留学，毕业后会自然而然地定居在那儿。

这就意味着，如果你是一个普通人，去一个地方留学很有可能也就意味着将会在那里长期工作定居、抚养下一代。

如果真的有这样的「惯性」存在，那去什么地方留学这个问题就变得复杂得多了。我们不仅需要关心未来几年，更要关心未来几十年这个地方将会如何发展，是否适合在这里长期居住、儿孙满堂。

把这个问题换一种问法就是，有没有这样一些「理想」的国家或地区，可以对于一个普通家庭来说尽量保证未来几十年的幸福？

王缉思教授在其近著《世界政治的终极目标》中，恰好也讨论了「理想国的标准」这个问题 —— 看来要想把中美关系研究得深入，涉猎真的得称得上是「博大精深」才行，涵盖政治、经济，甚至哲学。我还是来摘抄一段他的原文吧：

「一个成功的、令人向往的国家应当是：第一，没有严重的外部和内部的安全威胁，国内政治稳定，暴力犯罪率低；第二，国家和民众都比较富裕，经济稳步增长；第三，国家有相对统一的信仰体系、道德准则和主流价值观，同时包容一部分公民所奉行的其他信仰，公民对国家认同度高。第四，公民之间贫富差距较小，公民平等在教育和社会保障体系中得到较好体现，社会不公能够通过法律和政策调整得到矫正，抑止官员腐败；第五，公民的自由权利得到充分保障，个人自由同民族、国家的自由相一致。」

如果以这样的高标准严要求来衡量，北欧国家 —— 比如丹麦 —— 一定可以金榜题名。我的偶像刘瑜老师为美国斯坦福的政治学家福山的著作《政治秩序与政治腐败》写的导读「如何到达丹麦？」，讲的就是如何到达丹麦这种国家如童话般的境界 ——「有法治、又民主，政府还高效而廉洁」。

丹麦或其他北欧国家虽然不错，可惜我有点儿怕去一个不说英语的陌生国家，也懒得花时间再去学一门外语 —— 真的，我觉得那些可以在非英语国家长期定居的中国人都非常令人敬佩。

这么说来，如果出国去一个英语国家留学继而长期居住，选项就所剩无几了：英国、美国、加拿大、澳大利亚、新西兰。

这些选项中，很多人最终还是去了美国。

##### 三

二十八岁那年，我在美国留学，周围的人基本毕了业都留在了美国。我则反其道而行之，决定去加拿大，一个我从来没去过的地方。

为什么要舍近求远呢？

我曾仔细研究过美国和加拿大的区别：两国的移民政策、医疗系统、还有退休制度，都完全不同。最后得出了一个结论：虽然两个国家都远远不能算是「理想国」，但是从我这样一个普通人的视角来看，加拿大比美国更适合长期定居。

我们拿退休保障制度当一个简单的例子来聊聊为什么吧。

美国联邦政府的退休金制度叫 social security。如果是公司的雇员，每年需要扣除工资的 6.2%，直到 137700 美元的收入上限，公司还要同时再支付同样一笔钱。也就是说，如果年薪超过了 137700 美元，每年要从自己应得的收入中拿出一万七千美元交给政府。六十六岁退休年龄一到，如果工作了三十五年，可以最多每月领到三千美元左右的退休金。

如果我们简单一算，会发现这个退休金制度不是很合算：三十五年交了六十万美元，退休每年只能拿回来三万六千美元，需要至少活到八十三岁才能把本金收回。可是如果自己拿六十万美元去投资，总是会有投资分红收入的，怎么感觉给了政府就没有利息了呢？

其实还真是这么回事儿。年轻人每年交给 social security 的钱，美国政府会先给退休后的老年人发退休金，如果有剩余则去买国债。也就是说，收入减去支出余下的钱，并没有去投资，而是借给政府花掉了。

随着平均寿命越来越长，人口逐渐老化，十年前支出就已经超过了收入，预计再过十几年，就算可以把以前借给政府的钱全拿回来，也都会尽数花完。那时候这个退休金制度是否会发生变数，就不好说了。

反观加拿大的退休计划 Canada Pension Plan，把雇员和公司交的钱加起来，每年最多只需要给政府交五千八百加元。而六十五岁退休年龄一到，最多每年可以拿回一万四千加元，活到八十一岁就可以把交过的本金收回。

两者相比，我更愿意给政府少交点儿，到退休后也少拿点儿。

更为重要的是，加拿大把收到的退休金交给一个叫 Canada Pension Plan Investment Board 的公司去投资，在全世界买了不少现金流还不错的产业，比如机场、输电线和高速公路。这样基本可以保证无论人口如何老化，任何时候都不会没钱发退休金。

您可能会想，这一个月才一千多块钱，不够花啊？

其实政府的退休金，平时虽然只不过是「锦上添花」，可一旦到了山穷水尽身无分文的时候，还是可以保证最基本的生活的。而恰恰是因为有了这样的基本保障，一辈子就不需要特别节省或者投资，可以有多少钱就花多少钱，尽情当一个「月光族」，不怕「outlive my money」。

有多少钱全花光 —— 这是多幸福的一件事儿啊。

##### 四

头一次从美国长途开车去加拿大的那天晚上，一路上基本漆黑一团，没有路灯，也没有导航和手机。直到远处渐渐看到了万家灯火，我才知道多伦多已经快到了 —— 这里没有亲人，也没有朋友。

其实，无论是去哪里留学，还是到哪里定居，说不定答案都非常简单。

哪里有你喜欢的馆子，有你多年的友情，有你爱着或者想追求的人，就去哪里。

如果那儿正好酷似童话般的丹麦，安全、富裕，可以安安稳稳地做个「月光族」，那当然就更好啦。

<div align=right>
2020 年 12 月，香港
</div>

