---
title: 知识青年
weight: 5029
slug: 为祖国健康工作五十年/知识青年
目录:
  - 06为祖国健康工作五十年
标签:
  - 2022年
---
> 你好李老师，我非常喜欢你。
>
> 今天北大一教授说，青年失业率已经逼近百分之二十。想向你请教一下，如何看待青年的就业问题？希望你的这篇文章，能从历史或者宏观的角度，讲讲在这样的环境下，青年人如何平复找不到工作的心态。谢谢李老师，希望能得到你的回复。（问题来自微博私信）

「能从历史或者宏观的角度」—— 感觉你这问题怎么有点儿像高考作文题啊。

##### 一

1933 年，美国正处于大萧条时期，失业率居高不下。就职仅仅两个月的罗斯福总统，向美国国会提出了一项全新的动议：由政府出资，雇佣未婚年轻男子参加一个叫「Civilian Conservation Corps」的组织，简称「CCC」。这个组织的活动保证不会与任何已有的成熟行业竞争，而将从事「林业、防止水土流失、防洪等项目」。

虽然罗斯福希望 CCC 的工作对美国有用，但这其实不是重点。就在一年前，罗斯福的前任胡佛总统（Herbert Hoover）被迫部署军队来驱散第一次世界大战中失业的退伍军人在华盛顿的游行。罗斯福心里很明白，数以百万计的失业者是多么危险。

国会立马就批准了罗斯福的这项动议。在三个月内，有 25 万年轻男子参加了 CCC，住在全国各地营地的帐篷里。只有军方才有足够的能力来管理这么多人，所以罗斯福让麦克阿瑟将军来全权负责。

在这以后的九年里，CCC 彻底改变了美国美丽富饶的农村。大约三百万年轻男子参加过 CCC。他们在野外坚持不懈地与森林大火作斗争，种植了三十多亿棵树，修建了十二万英里的公路和一万三千英里的小道，全新铺设了八万九千英里的电话线，在数百个州立公园修建了各种小房子、鱼类孵化场和野生动物保护区。

这三百万人每周六天早起锻炼，过着有点儿像童子军也有点儿像军营的规律生活。每位员工每月收入大约 30 美元，并一律必须将其中 25 美元寄回家。虽然大多数人刚开始工作时营养不良，但由于这样军营一般的规律生活，第一年平均体重增加了十二磅。

CCC 被证明是大萧条时期最受欢迎的政府计划。

##### 二

我第一次读到这段「人定胜天」的历史时，竟然有点儿悠然神往。

罗斯福的这项计划简直就是教科书般的神来之笔：几百万青年人不仅有了工作，还在军营般的规律生活中提高了体力和技能，培养了组织性纪律性，将来的一生受用无穷。

这简直就是所谓「躺平」的镜像反面啊。

我无端地认为，在当年那经济大萧条的年代，每一个人可以做到的事儿，相对大环境而言，是极其渺小的。但是人多了铁锹多了，要铺的路要修的桥，早晚有一天可以通车。

所以，与其天天关心时局，不如先从自己做起，从小事做起，从六点起床锻炼做起。与其「躺平」—— 这个流行词的具体含义其实我到现在也没有完全明白 —— 不如问问自己到底具备什么别人不具备的学识、才干和能力，可以让市场的天平早晚有一天会向自己倾斜。

说来说去，找工作其实和找对象差不多，都是一个概率问题。如果你是个阳光帅气健谈的小伙子，早睡早起、经常运动，虽然无法保证有喜欢你的姑娘，但是概率自然会高不少。如果你喜爱而且擅长你的专业，不断提高自己的专业水准，你能找到工作的概率自然也会高于常人。

「要创造我们的幸福，全靠我们自己。」有首歌脍炙人口，其歌词这样写道。

##### 三

我二十多岁的日子，大部分是在美国一个美丽的农村度过的。

有一年我参加了学校一个叫「中国学生学者联谊会」—— 简称「CSSA」—— 的组织，连夜和当时 CSSA 的主席褚明宇同学一起撰写排版一本叫「新生指南」的小册子。

小册子里面的内容不太记得了，不外乎是罗列一些办理入学手续还有租房买菜什么的注意事项。

只记得凌晨时分，褚明宇为了这本《新生指南》的序言怎么写，沉吟了许久。

天快亮了，他终于大笔一挥，开门见山，一语石破天惊：

「伟大领袖毛主席教导我们：知识青年到农村去。」

<div align=right>
2022 年 5 月，多伦多
</div>