---
title: 导师
weight: 5030
slug: 为祖国健康工作五十年/导师
目录:
  - 06为祖国健康工作五十年
标签:
  - 2022年
---

我 22 年前在伊利诺伊大学的研究生导师 Klara 最近准备参与评选一个 Women in Science 的国际奖项，想起了我，邀请我写一封推荐信。

写这封信的时候，我又想起她修改论文时龙飞凤舞的字迹，想起她晚上 11 点多发的那些「come up to my office」的邮件。一个优秀的导师，应该既有大局观，又能在细节上下功夫；既能自己从早到晚努力工作，又能对待学生「像春天般温暖」。

Klara 就是这样的导师。

<div align=right>
2022 年 5 月，多伦多
</div>

——

May 29, 2022

To whom it may concern:

It is my great pleasure to write this letter in strong support for Professor Klara Nahrstedt’s nomination for the L’Oreal-UNESCO For Women in Science International Award. Klara has been my thesis advisor at Illinois throughout my Master’s and Ph.D. studies, for a period of four years from 1996 to 2000. Since 2000 and immediately following my graduation, I have been teaching at the Department of Electrical and Computer Engineering, University of Toronto, where I am currently a Professor, IEEE Fellow, and the Bell Canada Endowed Chair in Computer Engineering. In my professional career, I have published over 450 co-authored research papers, won several awards, and achieved an H-index of 84 according to Google Scholar. With H-index as the metric, I am currently ranked #12 in Canada in the field of computer science, according to [research.com](https://research.com/u/baochun-li).

At Illinois, I have benefited tremendously from Klara’s supervision, advice, and stewardship. Klara’s influence on my student experience and my ensuing professional career was so significant that it simply could not be overstated. With her mentoring and leadership, I have grown from a new graduate student with very little experience on research to a mature researcher winning a best paper award, all within a short time span of four years. Suffice it to say, without Klara’s supervision at Illinois, it is impossible for me to start my academic career at Toronto in the first place, let alone remaining productive throughout my career. She has had a life-changing impact on my academic and professional career.

I believe that an excellent researcher should be both visionary and paying attention to detail. Klara taught me both with her mentorship. With respect to research vision, she consistently demonstrated an excellent grasp of the “big picture,” especially when it comes to new, emerging, and interdisciplinary areas of research. I have benefited tremendously from Klara’s vision as I worked on my PhD thesis work, and from our numerous meetings and discussions in her office. Ultimately, one of our papers won the Leonard G. Abraham paper award from the IEEE Communications Society in 2000, and was cited more than 500 times since its publication in an IEEE journal.

Klara also paid a lot of attention to detail when we were working together on research. She enjoyed revising my research papers by handwriting. As she discovered problems from minute typographical mistakes to structural and clarity concerns, her handwritten communication has always inspired me and refined my research skills effectively. She was particularly demanding with respect to timely and effective communication, both in more formal talks and over more informal email messages. She cared about interpersonal and communication skills when her students, including myself, attended international research conferences. But more importantly, she was as nice as anyone to her students in the research group, caring passionately and deeply about their career choices when their graduation drew close.

I have read a number of bitter stories after I started teaching at Toronto, told by graduate students and their supervisors in other universities. Some students developed negative feelings towards research and towards academia in general, some even poked fun at the harshness towards getting a Ph.D. degree. I can honestly, and proudly, say that I experienced none of these in my own graduate studies. My own experience felt more like sailing smoothly in the Caribbean, rather than stalling in the midst of a winter snowstorm. I was always fully charged, upbeat, and energetic to attain my research goals. In hindsight, though there were turbulences along the way as some of my research papers were rejected even after putting in the hard work, the supporting role that Klara played was so reaffirming and so warm, I never felt discouraged. This continued well into my academic career after I started at Toronto, as I inherited the same philosophies when mentoring my own students, over sixteen of which started their own academic careers at universities around the world. I guess I was lucky from the very beginning, and I hope that my experiences at Illinois are convincing enough to offer my strongest support for Klara’s nomination for the L’Oreal-UNESCO For Women in Science International Award.

Sincerely yours, 

<div align=left>
Baochun Li, Ph.D. (Illinois, 2000)
</div>

<div align=left>
University of Toronto
</div>
