---
title: 老毕
weight: 2009
slug: 芳华已逝面目全非/老毕
目录:
  - 03芳华已逝面目全非
标签:
  - 2020年
---
在这万众一心地关注每天又新增多少确诊案例的时局之中，不知道为什么，我竟然想到了老毕。

也许是因为，再过几天，就是老毕去世一周年了。

老毕是我在清华的大学同学。我们这些年的交情，既谈不上是「莫逆之交」，也不至于仅仅是「点头之交」，我想大概可以算是「合影之交」吧。我们的学术研究方向相仿，算是「小同行」，所以因为开会，每隔一两年总有机会见上一面。老毕有一个良好的习惯：每次开会见到我，都要跟我合影留念。最后一次见到老毕是他来多伦多参加一个学术会议，正好是我牵头组织的。我翻开当年的相册，轻而易举地找到了我们的合影，是与他同来的一个学生帮我们用手机拍的。照片中的老毕神采奕奕，笑容可掬。

老毕大学时就有点儿胖。他在我的印象中永远显得和蔼可亲，大概是因为他爱笑的缘故 —— 微胖而又爱笑的人容易让人觉得亲切。老毕又是当年我们系的党支部书记，他慈祥的笑容中自然地多了一点儿领袖魅力。当年复习准备 GRE 时，俞敏洪在新东方给我们讲「charisma」是「中国升起了毛泽东」的那一刻，我正好就想起了老毕。

老毕和我都可以算是土生土长的北京人，但是除了这一条，我哪一方面都没法儿和老毕相比。老毕是北京八一中学的高材生，品学兼优，高中时就入了党，并保送了清华大学计算机系。如果没有入选奥赛，保送清华当时非常难 —— 我所在的中学也号称算是全国重点中学，当年一个保送清华的名额都没有。大学毕业后，老毕留校读博士学位，仅用了四年就读完了，可以算是「书生意气，挥斥方遒」的样板。

大学有一年，我在《马克思主义哲学》这门课中学得很不错，最后的学期成绩接近满分。这说明与其学工科，我其实早就应该去学文科 —— 大一的《中国革命史》我也相当擅长。可以看得出来，老毕很欣赏我，当年经常鼓励我写入党申请。有一次在三教的一个教室又聊起来这事儿，我很不好意思地跟老毕说，我觉得我自己还不够格，很多的东西还只知道一点儿皮毛，需要再进一步努力提高自己的认识水平。

就像有的人性格外向有的人则内向一样，我觉得老毕一直是认真负责的「入世」性格，而我则说得好听点儿叫「出世」，说得不好听一点儿则是一个做一天和尚撞一天钟的「逃兵」。老毕博士毕业在美国进修了几年，继而顺理成章地在清华任了教职。自此，他在清华培养了一批又一批的学生，直到去世之前一两个月还在工作。按一篇纪念他的文章中的话说，「他是我目前见过对科研最拼命的人。」

老毕去世之后，大学的同学们以他的家庭困难、孩子长期需要照顾为名义，发起了募捐。而纪念他的文章，讲述的故事则清一色的是他直到最后一刻，还坚守在教学和科研的岗位上，还在关心着论文是否能及时修改好，是否能投到一流的国际会议上发表。

老毕和我是「合影之交」，但我们走过的路则大相径庭 —— 是一位优秀的党员和一个早早跑到国外的逃兵的区别。老毕去世转眼快一年了。时间飞快地流逝，时局则尽是变数，像万花筒一般，每一天都不同，令人目不暇接。一两年后，也许不会再有人想起老毕来，就好像那时也不会再有人想起现在眼前曾发生过的事儿一样。那时老毕大概早已成了百度百科的一个条目，而他的名字，渐渐地成为了历史百科全书中的一条脚注。很多年后他的子女和他曾影响过的学生依稀可以想起来的，不是他拼命写出来的科研论文，而多半儿会是他当年显得有点儿慈祥又有一点儿领袖魅力的笑容。

老毕和我是「合影之交」。他是一位「够格」的党员，也是一个有益于人民的人，值得我向他学习。他让我想起了米特・罗姆尼前几天在弹劾案投票前演讲中所说过的一句话：「我会告诉我的子女和他们的子女们，我已经尽了我的最大努力，没有辜负我的祖国对我的期望。」

<div align=right>
2020 年 2 月，多伦多
</div>

