---
title: 爱情麻辣烫
weight: 1027
slug: 将爱情进行到底/爱情麻辣烫
目录:
  - 02将爱情进行到底
标签:
  - 2019年
---
> 李老师您好，好久没见您在微博上分享问答了。最近也有一个困惑想听听您的看法：两个人在一起到什么程度就可以结婚了？什么原因可以促使一个人下定结婚的决心？（问题来自微博私信）

##### 一

你的问题让我想起了二十年前的一部电影，叫《爱情麻辣烫》。

按理说，二十年前的电影绝对可以说是「老」电影了。可是在我的心目中，这部电影一点儿也不老，反倒是颇为入时，可以说是国产电影中的一部经典，和三十年前的《霸王别姬》有一拼。

该片是张扬的处女作，可我觉得和《洗澡》并列，可以说是他最好的作品 —— 就好像慕容雪村的第一部小说也是他最好的一部小说。

电影一开头是王学兵陪着未婚妻和未来的岳父母去吃麻辣烫：「今儿的火锅太辣了。」

然后镜头一转，开始了五段互相之间似乎没什么关系的故事。「声音」里的男生爱上了同班一个身穿白裙子的女生；「麻将」里三个老头儿一起和老太太相亲；「玩具」里刚结婚的一对儿不打不成交；「十三香」里的中年夫妻在孩子的泪水中离婚；「照片」里两个人终于决定在一起时，竟然一分开就再也找不到回家的路了。

我觉得张扬的厉害之处在于五个故事排列的顺序。少年时的相思开场，紧接着的是老年时的相亲，新婚时的相对无言，中年时的分离，最后是青年时的相爱。

而五个故事的弓弦，是由王学兵演的这对准备结婚的情侣串起来，也是以他们结婚的婚礼收尾。

张扬好像是在告诉你，按照他安排的这个顺序想明白了这五个故事，你就可以结婚了。

##### 二

你的问题有两种可能的解释：一种是打定主意要结婚，但是不知道什么时候结婚为好；另一种是还不太确定是否应该和一个男生结婚，不确定和他结婚以后会不会幸福。

第一个问题我的答案是：结婚越早越好。

你一定会问：那暂时还没钱买车买房办喜酒怎么结婚？

简单啊。没有钱买房可以先租房住着，没有钱买车可以买辆二手车，没有钱办婚礼可以从简。

总之两个人都没钱也完全没关系，照样可以早早结婚。甚至越穷的时候结婚，将来的婚姻就越可能源远绵长，即使真的分开了，也会友谊长存。

因为没钱的时候结的婚，经常能体现两个人的一种特别牢靠的默契 —— 而婚后的天长地久，往往依靠的正是这种「怎么又想到一块儿去了」的默契。

而第二个问题 —— 在说不上知根知底时如何下定决心和一个男生结婚 —— 就不是一两千字能聊的完的了。你看连张扬都说了：「相爱是容易的，相处是困难的。」而想「长期共存」，你得找一个优点多于缺点、比较靠谱的好人。

那什么样的男生比较靠谱呢？我有一个自作主张不一定对的判据供你参考：平常愿意经常自己做饭的男生 —— 无论做得好吃不好吃。

##### 三

买三角钢琴的时候我听说，上好的钢琴用到的杉木多是阿尔卑斯山高海拔地区背阴处采伐来的，那里终年阳光不多，树木长得极其缓慢，每英寸需要长二三十年；但是又极其均匀，年轮之间的距离几乎一致。

婚姻其实也和钢琴有点儿像：上好的婚姻稳扎稳打，极其缓慢而又极其均匀地成长。

就好像西方婚礼的誓言里说的：「for better and for worse, for richer and for poorer, in sickness and in health, to love and to cherish, till death do us part.」

电影《爱情麻辣烫》「声音」那一段里，有一段高中男生王艾和高中女生高圆圆的经典对话录音剪辑：

「你喜欢和我在一起吗？」

「喜欢呀。」

「真的喜欢吗？」

「真的喜欢呀。」

<div align=right>
2019 年 9 月，多伦多
</div>
