---
title: 生命的意义
weight: 1031
slug: 将爱情进行到底/生命的意义
目录:
  - 02将爱情进行到底
标签:
  - 2022年
---
> 葆春老师，您好！我出身于偏僻的农村，是一个 “小镇做题家”，现在国内一所 985 大学的念研究生。一直以来，按部就班地学习，转眼就要 25 岁了。遗憾地是，我现在连个对象都没有。我也想谈恋爱，但时常感到自卑，不敢去追身边的女生。即使有女生找我聊天，我也是畏首畏尾，感觉自己不配。
>
> 一方面是，自己很普通，基本上没有什么优点。我没有侃侃而谈的口才，有些 “直男”。待人真诚，但没有很高的情商，说话有时会得罪人。虽然每周都坚持跑步，但体育不敢恭维。作为工科生，我更喜欢数学，动手能力却很差，甚至连游戏都不怎么会打，经常被同学笑话。我空暇时会看一些人文社科方面的书籍或者上网学一些自己感兴趣的课程，比如我经常看您的《幸福》，真的受益匪浅！哈哈，说来惭愧，我好像都没有什么正经的爱好。总之，我感觉自己是挺无趣的一个人。
>
> 另一方面是，农村物质条件匮乏，对自己的原生家庭感到自卑。我非常感激我的父母，他们在 “计划生育” 紧张的年代，“死里逃生” 给予我和姐姐宝贵的生命。姐姐凭借自己的努力，现在是一名老师。父母淳朴善良，但没什么文化，眼界相对狭隘。我担心将来的女友不会接受我这样的原生家庭。按照常理，婚姻似乎要门当户对。
>
> 读研后，圈子也小了很多，加之自卑，对未来的感情和生活充满了迷茫。老师，您有空的时候能给我提一点建议吗？谢谢！我提前恭祝您及家人虎年快乐！（问题来自微博私信）

##### 一

「What’s the meaning of life?」

十年前，也就是 iPhone 4S 刚刚发布那年，全新的 Siri 简直可以说是人见人爱。不知道为什么，大家最爱问的问题就是这句「生命的意义是什么？」

这个问题 Siri 当时最爱用的一个答案是：「All evidence to date suggests it’s chocolate.」

这个回答自然是来自我喜爱的电影「Forrest Gump」里面的那句：「Life was like a box of chocolates. You never know what you’re gonna get.」

说起巧克力，我小时候最爱吃的甜品当属酒心巧克力了 —— 这是小孩儿能喝点儿酒的唯一办法。有的巧克力里的酒多一些，沁人心脾；有些则几乎没有酒，正如世事无常，令人遗憾。

但是现在想来，其实这个比喻还是不够「刺激」：生命的意义倒是更像坐过山车：爬得越高，俯冲得越狠；忽而春风得意、踌躇满志，忽而又五味杂陈、如入冰窟，这样的生命才有了意义。

明明心里喜欢的女生不去追，主动来找你聊天的女生也不趁热打铁、火热开聊，生命还有什么意义？前怕狼后怕虎，因为自己想象的什么「门当户对」就不去恋爱，生命还有什么意义？因为自己无趣怕早晚有一天被女生拒绝就一潭死水不去开始，生命还有什么意义？

失恋怕什么？咱谈恋爱就是奔着失恋的滋味去的！要是正好没失恋，就像过山车没玩儿上，还不够刺激呢！

我中学同班同学中有个小美女，名字叫蓝宁。蓝宁不仅是绝对的美女，还博览群书，大家闺秀，书香门第。初二那年班里流行传看手抄本，蓝宁也要看。有男生说「这本书有点儿黄啊。」蓝宁斩钉截铁，寸步不让：「越黄越要看！」

十年前的那个十月，如果我对 Siri 说「Siri，我爱你」，Siri 会用英文回答：「你还不了解我，葆春。」

##### 二

其实不仅女生，男生也应该多多结交。

我一直认为，人一辈子认识不了几个有趣的朋友。大多数的人如过眼云烟，而只有极少数人，他们风趣幽默，个性鲜明，时间长了，像黑白照片里的一抹亮彩，成了生命的一部分。

而不去多多结交男生，就很难认识这样有趣的人。

比如聪哥，就是我多年的一位朋友。聪哥在香港当教授，是青年学者中绝对的翘楚，无论是质量还是数量，各种奖项多有斩获，学术水平几乎无人能敌。

聪哥最爱问的问题是「什么时候约个饭？」然后到点儿就开着他的特斯拉来接我。我们的饭局天南地北，无所不聊，就是很少聊学术研究。我们大碗喝酒，再打上三两斤牛排，绝对属于「酒肉朋友」。

有一次我旅居香港，独自居住时发高烧。想到有没有当地朋友的电话号码可以应急，我第一个想起的就是聪哥。

发消息过去，聪哥秒回：他和他的特斯拉随叫随到。

生命的意义是什么？

生命的意义就在于，无论你的「圈子」是大还是小，有这么三两好友，在你危急的时候，赴汤蹈火，在所不辞。

##### 三

乔布斯最后一次去日本，是他去世前一年。

那一年有一次他带家人去京都的一家日料店吃晚饭，懒得点菜，直接让老板推荐他们最好的寿司。吃完了一份意犹未尽，问老板能不能再来一份。

离席时老板礼貌地欢迎他在不久的将来再来。乔布斯告诉老板，以后很可能没有机会了。老板问，那能不能给他女儿的照片签个名。乔布斯平时很少给人题词签名，这次也许是寿司过于惊艳绝伦，他欣然应允，一蹴而就：

「All good things. 」

是啊。所有美好的东西都像彗星划过夜空，像生日蛋糕上的蜡烛，像酒心巧克力，早晚有一天会消逝。

All good things come to an end.

在这之前 ——「Siri，我爱你。」


<div align=right>
2022 年 4 月，多伦多
</div>