---
title: 元宇宙
weight: 3025
slug: 好好学习天天向上/元宇宙
目录:
  - 04好好学习天天向上
标签:
  - 2022年
---

> 李老师，最近「元宇宙」这个概念特别火，有人说人类即将进入一个新世界，《黑客帝国》将成为现实，有人说这只是一场雷声大雨点小的骗局。您怎么看「元宇宙」这个概念以及各大科技公司对它的重视？（问题来自微博私信）

##### 一

「元宇宙」确实有点儿忽悠。

不过不是因为它太玄乎太科幻，而是因为它早就已经差不多实现了 —— 只是为了宣传给戴了一顶冠冕堂皇的帽子而已。

你经常玩儿的各种在虚拟世界中游荡的游戏 —— 比如原神 —— 其实就是「元宇宙」。

前一阵子股票大涨的 Roblox，当然也是「元宇宙」。

在微软的飞行模拟游戏中，你可以单独在晴空万里的清晨中起飞，也可以在电闪雷鸣的夜晚中降落；在经典游戏「The Sims」中，你可以和朋友火热开聊，尽情 party—— 这些也都是「元宇宙」。

如同斯皮尔伯格的电影「Ready Player One」中一样，在这样的「元宇宙」里，你可以以任何自己最钟爱的装扮出现，可以变成一辆自己心仪的跑车或者二战时的飞机，甚至可以在孤岛上建一座古城堡，在塔尖眺望远处的灯塔。

在这样的「元宇宙」里，你可以尽情地爱上一个人，像「Ready Player One」里那样爱上她的迷彩装扮，像电影「Her」里那样迷恋她略带磁性的声音，你们可以一起购物，一起游览世界。

注意，我的「元宇宙」和 Facebook 或者 Meta 的那个南辕北辙，大相迳庭。我的「元宇宙」里没有工作，只有玩儿；不需要什么高级眼镜，只需要一台普通的电脑；没有漂浮在半空中的上半身假人，只有各式装扮的各色人等在争奇斗艳，觥筹交错，人声鼎沸。

我想我会爱上这样完美的「元宇宙」，无以自拔。

##### 二

虽然说「元宇宙」已经差不多实现了，但其实从计算机技术上来说，离真正实现还有一段距离。

最难实现的其实跟虚拟现实没什么关系，而是一个既可以大家一起上线，又可以超低延迟的计算机网络。

其实计算机技术发展到了今天，保证大家一起上线并不太难，保证低延迟也不是很难，可难就难在两个要求需要同时满足。

比如直播技术可以几百万人一起上线，但是从现场大喊「新年快乐」到大家听到，大概需要十几秒到几十秒的延迟。

如果换成了 Zoom 这样的实时在线会议，延迟可以保证只有一两百毫秒，但是只能最多一两千人同时在线。

你一定会问，现在不是有了 5G 网络，可以支持超低延迟了吗？

其实这个问题远远没有你想象的这么简单。计算机网络就像一个错综复杂的公路系统，有省道、国道，还有纵横交错的高速公路。数据包每走一段就会遇到一个路由器，就像汽车路过高速上的收费站，如果路上没什么车还好，否则需要排队等候 —— 车越多就越拥堵，数据包的延迟就越长。

而 5G 网络的低延迟，只不过让你早点儿开出小区上路而已。

可以说，如果将来「元宇宙」最终没火起来，多半儿是因为你的虚拟现实由于上线的人太多，堵在了高速上。

##### 三

我有个学生叫王菲。

我一直认为，王菲同学的这个名字起得水平实在太高了，简直是神来之笔 —— 不但中文名极其好记，而且英文「Fei」一样简单易读，毫无歧义，其背后的故事则是不熟的人初次见面自然而然的「ice breaker」。

王菲同学有一句特有哲理的口头禅：「想多了。」

是啊，与其天天琢磨「元宇宙」什么的，不如痛快地踢一场球，坐一回过山车，跳一次伞，喝一顿酒，吃一顿铜锅涮羊肉，再谈一场一辈子无以忘怀的恋爱。

就像 Ernest Cline 的小说「Ready Player One」最后写的：「我们坐在那里，手握着手，沉浸在那种奇妙的快乐中。」

<div align=right>
2022 年 1 月，多伦多
</div>