---
title: 向上移动
weight: 5038
slug: 为祖国健康工作五十年/向上移动
目录:
  - 06为祖国健康工作五十年
标签:
  - 2025年
---
##### 一

我有一个学生，平常爱用大模型。前一阵子写了个给几位教授的邮件，内容也是用大模型先生成，再自己详加修改。想法虽然挺好，可惜大模型犯了一个小错误：它把 DOE 自作主张展开写成「Department of Education (DOE)」 — 其实也不是完全没道理，学校的邮件嘛 — 但是在多伦多大学「DOE」代表「Departmental Oral Examination」。由于这是学校内部的简称，大模型不太可能知道。

学生没检查出来，等我收到抄送才看到，已经晚了。

所以啊，人工智能和大模型虽然发展迅速，日新月异，怎么利用，还是挺有学问的。

7 月 3 日，我将做客褚明宇的「向上移动」第三季，聊聊如今的人工智能和大模型。

##### 二

我一向不怎么喜欢特别忽悠的那种所谓「卖课」的广告。

自从 2017 年的第一季，褚明宇的「向上移动」一直不是一个产品，一门课程，而是一个社区。

怎么说呢，无论是第一季的文字，还是后来的直播，这个社区从来没打算过要教点儿什么内容，而是以交流为主。

在现在微信群漫天飞舞的时代，其实真正有点意义的在线社区，我感觉倒是越来越少了。大多数微信群反映的是已有的社会关系 — 同学、同事、校友 — 而非随机生成的全新社区。在人工智能领域中，大多数微信群是「exploitation」，而非「exploration」。

你这时一定会说：这不就是粉丝群嘛，见过见过。

我觉得也不尽然。「粉丝」这个词儿有点儿被滥用了，但其实不可能所有人都完全认同褚明宇的观点。我感觉这个「向上移动」社区更像是由对生活对工作比较爱较真儿，比较乐于问个为什么的朋友们组成的。

对，「朋友」这个词儿可能比「粉丝」更贴切。刚开始是陌生人，时间长了，就慢慢儿成了朋友。

##### 三

褚明宇的这个社区，还请到了我们上学时的共同好友张戎跟大家交流一场。

张戎是个神人。清华上学时就是十杰候选人，后来学了机械工程，玩过汽车，还去斯坦福读了 MBA。知乎上的文字既有工程师的严谨，又掺杂一点儿北京人的幽默。

他去年写了本书，插图都是他亲手画的。我看完一直想写个书评，由于工作繁忙，到现在都还没动笔。

在这人工智能的大时代，我们更需要褚明宇和张戎这样的朋友：他们一直立场鲜明、论据靠谱、逻辑清晰。

不是所有人都是「博主」、「主播」。有极少数人，你不一定同意，但会经常想起他的观点。只要想得到，你就会去想他们说的是不是正确的，而听过想过，就比完全没听过没想过更有意义。

如果「粉丝」是这么定义的话，那我也算褚明宇和张戎的「粉丝」之一。

下个月线上见。

<div align=right>
2025 年 5 月，多伦多
</div>
