---
title: Mr. Right
weight: 1029
slug: 将爱情进行到底/mr-right
目录:
  - 02将爱情进行到底
标签:
  - 2019年
---

> 李老师，我是一个 25 岁的女生，研究生毕业工作一年多，单身了四年左右。我发现，找对象太难了，喜欢上一个人并且让这个人喜欢上你也太难了。我的好闺蜜们都陆陆续续的找到了稳定的交往对象，并且向结婚迈进，像是约定好了一样。所以这件事好像成了我一个缺点，她们也经常催促。这期间也有男孩喜欢我或者表达好感，我也迫于压力逼迫自己去积极相处，但是结果也都不尽如人意。和不喜欢的人在一起，实在没法快乐。
>
> 最近我们部门的一个入职不久的新员工，也是小学弟，时不时找我聊天，大概持续了两三周。晚上下班以后我们微信上总能聊的很开心，并且小学弟本人也高高白白俨然就是我喜欢的类型，所以每天都很开心。
>
> 最近因为有喜欢的明星的电影上映，我就开玩笑发消息给小学弟说让去支持支持，他回复的也很令我开心，想我带他一起看。真的很开心，心里面甚至忍不住狂喜，觉得这次爱情可能真的要降临到我头上了。今天晚上我们一起出去看了电影，可是真的和真人去交流，却发现火花少的可怜，他似乎也并没有对我很上心，真的是在吃着东西开开心心看电影，和我的沟通交流也完全和之前不太一样。总之看完电影也就各回各家了，我非常非常难过失望。同时，他也没有在像之前那么热情在微信上和我聊天了。
>
> 我好困惑迷茫，现在的我要怎么心理建设，我还会去恋爱么，还有能力还有机会去恋爱么？我好担心我的全世界只剩我一个人孤孤单单。（问题来自微博私信）

##### 一

刚刚读到你提到自己二十五岁、「单身四年」的时候，我隔着手机的屏幕，都能体会到你那份有点儿焦虑不安、想「与时间赛跑」的心情。

可你发现没有，找个合适的男生谈恋爱，跟到健身房运动减肥差不多：你再着急也没什么用。就如同减肥不是一天两天就可以见效一样，谈恋爱也不是一天两天就能谈成的事儿；就如同减肥会有反复一样，谈恋爱也会分手、会痛苦、会和好如初。

不过你这种焦虑的心情我非常可以理解。估计你的心里总是惦记着，在多少岁之前一定要完成这件事儿，就像是一个「deadline」。时不我待，只争朝夕，离你心中的这个「deadline」越近，你就越觉得希望渺茫。

但其实就像健身减肥是一辈子的事儿一样，谈恋爱也是一辈子的事儿，没有什么「deadline」。就像健身减肥可以随时开始一样，谈恋爱如果结局幸福圆满自然好，如果不尽如意，也一样可以随时开始，重新再来。

很多人喜欢说「人生苦短」，我完全不同意：人生一点儿也不短 —— 人生很长很长，将来有的是时间，甚至长得有点儿让人不知道怎么打发。你想啊，假设你二十五岁开始工作，六十岁退休，能活到九十五岁，工作三十五年还算有事儿干，退休三十五年要打发时间，得玩腻多少游戏、看腻多少网红直播啊。

想明白了「着急其实没有用」、「时间有的是完全没必要着急」这两条「定理」，咱们就在「战略」上成功地藐视了「敌人」。

不过别忘了，要想好好地恋爱（或者实实在在地减肥），咱们还得在「战术」上重视「敌人」，把这个任务多快好省地完成。

##### 二

我不是很相信「一见钟情」。

除非这「一见」是指一上飞机偶遇就开始聊天，越聊越投缘，一直聊到越洋航班落地，还觉得有点儿意犹未尽。

我觉得谈恋爱要想谈到「合二为一」的境界，必须从了解对方开始。就连日常的小事儿 —— 譬如说买辆新车 —— 我们都倡导先做一些调查研究，更何况谈情说爱这样关乎幸福与否的大事儿。

而了解一个男生越多，你就越可能因为他的一些小小的不足之处把他拒绝：「不行不行，这位同学有点儿口吃。」「妈宝男坚决不能要啊。」「凤凰男也不行。」「这人也太能说了吧，有点儿油嘴滑舌。」「这人也太木讷了吧，我说十句他只回一句。」

我最近一直在准备买一辆新车，就差点儿犯了这个错误。刚开始买车的时候，我非常关注车是不是好看 —— 也就是所谓的「颜值」—— 但凡不好看的坚决不买。结果研究了一段时间我发现，好看的车都很贵，从买车到日常保养，贵到了让我觉得其实性价比很成问题。贵倒还在其次，很多豪华品牌其实可靠性不怎么地，要是开在路上出了问题，既不方便又不安全。而可靠性比较出众的车型，绝大多数都不好看。

等到我穷尽所有品牌的车型时才发现，我想找的那辆既好看又可靠、既物美又价廉、既加速快又超级省油的汽车，其实根本就不存在。

没有十全十美的车，也不会有十全十美的人。不擅长言辞的男生也许将来更适合相依为命，苦孩子出身的凤凰男也许前途不可限量。很可能啊，你好多年之后才发现，最初的那个不善言辞有点儿口吃的男生，其实才最适合你。

所以啊，其实谈恋爱不可能永远一帆风顺。我们要列一份详尽的清单，把每一位男生（或者女生）的优势和劣势仔细拆解一番。综合评估分数最高者，我们要本着「敌疲我打、敌退我进、敌驻我扰」的精神，百折不挠，排除万难，去争取胜利。

我终于选定了要买的新车 —— 是一辆超级难看的丰田。

##### 三

前一阵儿在飞机上偶然机会看了一个十几年前的老电影。这是一部浪漫喜剧，名字叫「27 Dresses」。

故事情节其实很简单，不用剧透都能大致猜到。Jane 非常喜欢当朋友婚礼上的伴娘，曾经当过二十七次，但自己却从来无缘「Mr. Right」。

当她第一次见到 Kevin 时，非常不喜欢他。而她一直暗恋着她公司的老板，却偶然结识了她的亲妹妹，两人打算火速结婚。

其实浪漫喜剧是非常不容易拍好的一类电影。主要是因为不同人对「浪漫」的感觉完全不同，有的人觉得感人至深就会有人觉得俗不可耐 —— 按我女儿的话说叫「sappy」。众口难调，想把电影拍得雅俗共赏着实不容易。像斯皮尔伯格「The Terminal」这样的上乘之作，难得一见。

我在飞机上完全没有想到，这样一部关于伴娘在婚礼上偶遇「男神」的传统爱情喜剧，我居然看得感动不已。

就像电影里面一样，无论早晚，我们每一个人总是能过上属于自己的那最特别的一天。

这一天的那个人也许和当初自己想象的完全不一样 —— 没有「颜值」、脾气倔强、不善辞令。

但是这一天总是会到来。

新年快乐。

<div align=right>
2019 年 12 月，多伦多
</div>
