---
title: 酒公墓
weight: 2013
slug: 芳华已逝面目全非/酒公墓
目录:
  - 03芳华已逝面目全非
标签:
  - 2026年
---

一位朋友前些天提起，想筹备一个活动，聊聊「幸福」这个词儿，问我有没有什么好的建议。

我第一时间想到的，竟然是这位朋友给我推荐的一本书：经济学人 2008 年左右出版的《讣告》（Book of Obituraries），书中收录了两百位各色人等的讣告。我想，幸福这两个字，可能只有在这本书中才能真实地感受到。至少，书中的人，知名也好不知名也罢，都早已仙逝，活着的人看看他们生前的故事，也会油然而生一种幸福的体验。

朋友说：「那会不会有点儿丧？」

我年轻时第一次读到一份感人至深的讣告，还是三十多年前看余秋雨所著的《文化苦旅》。这本书其他的文字都早已不记得了，只记得一篇《酒公墓》，寥寥数笔，记叙的是酒公张先生一生的故事。

搜索了一下，发现百度百科就收录了全文。相隔三十年后，我又看了一遍这篇讣告。看到张先生一听到文中的「我」提及金岳霖先生的逻辑思想，马上就「抖抖索索地把我的手紧紧拉住，说自己将不久人世」，希望「我」能替他写一方小字碑文。

>我问他小字碑文该如何写，他神情严肃地斟酌吟哦了一番，慢吞吞地口述起来：
>
>“酒公张先生，不知籍贯，不知名号，亦不知其祖宗世谱，只知其身后无嗣，孑然一人。少习西学，长而废弃，颠沛流荡，投靠无门。一身弱骨，或踟蹰于文士雅集，或颤慑于强人恶手，或惊恐于新世问诘，或惶愧于幼者哄笑，栖栖遑遑，了无定夺。释儒道皆无深缘，真善美尽数失落，终以浊酒、败墨、残肢、墓碑、编织老境。一生无甚德守，亦无甚恶行，耄年回首，每叹枉掷如许粟麦菜蔬，徒费孜孜攻读、矻矻苦吟。呜呼！故国神州，莘莘学子，愿如此潦倒颓败者，唯张先生一人。”
>
>述毕，老泪纵横。

《文化苦旅》出版后已经三十多年，余秋雨先生都已八十高龄。但是重读他的文字，还是一如当年，鲜活而令人动容：

>前年深秋，我回家乡游玩，被满山漂亮的书法惊呆。了解了张先生的身世后，我又一次上山在墓碑间徘徊。我想，这位半个多世纪前的逻辑救国论者，是用一种最潦倒、最别致的方式，让生命占据了一座小山。他平生未能用自己的学问征服过任何一个人，只能用一枝毛笔，在中国传之千年的毛笔，把离开这个世界的人慰抚一番。可怜被他慰抚的人，既不懂逻辑，也不懂书法，于是，连墓碑上的书法，也无限寂寞。

「确实会有点儿。」我说。

<div align=right>
2026 年 2 月，多伦多
</div>
