---
title: 纸质书
weight: 7038
slug: 柴米油盐酱醋茶/纸质书
目录:
  - 08柴米油盐酱醋茶
标签:
  - 2024年
---
昨天新买了一台相机。打开包装，发现没有纸质版的使用说明书，只给了一个电子版说明书的链接。

上次买相机还是十四年前。那时，包装里附上了英法双语两大本说明书，我还仔细研读了好长一段时间。这回没有了说明书可以翻阅，我坐在办公室的大屏幕前，全屏打开了刚下载好的电子版。虽然字大得出奇，也许是脑子还没适应，总是觉得看不下去。

正好，在「葆春和他的朋友们」微信群中，有人提到了纸质版的《幸福》。这本书是我五年前花了很多时间整理排版出来的。光是校对版就印了五六本，重头学了书籍排版技术，颇花了不少心思。可惜的是，那年只有机会寄出了两百本书，真的像当年微博里戏称的，成了「法拉利限量版」。这两年所有回国的航班都需要转机，由于怕转机丢失行李，每次回国都只带了随身行李，基本没有机会再带书了。

四年前，我又花了大量时间，把所有书里书外的文字，都整理发布在个人网站（baochun.ca）。这样想看这些文字的朋友，至少能够看得到。后来网站的代码一直在维护升级，搜索功能改了两版，现在总算是稳定下来了。唯一美中不足之处是，由于需要打开思源宋体这个字体，第一次加载网站速度不够快，需要等很长一段时间。

现在纸质书和 CD 唱片、录音机、胶卷相机、现金等大量智能手机出现之前的事物的命运一样，早已退居二线了。《幸福》虽然现在网站上有电子版，也没什么人真正有时间看纸质版了，我还是觉得纸质版有点儿电子版所没有的吸引力。不说别的，仅仅是中英文采用什么字体，什么字号，留白留多少，都能给读者带来不同的体验。我小时候父母在出版社工作，常年都负责编辑大学课本，从小就看着他们用图章来标注字体和字号的选择，也算是耳濡目染了。

这本书当时印刷「法拉利限量版」的时候，还有一段小插曲。书虽然没什么人看，我却执意希望能够用传统的胶印印刷。试了好几家印刷厂，都因为起印的数目太大而作罢。最后功夫不负有心人，终于找到一家位于魁北克省的印刷厂，量比较少也可以胶印，印好之后用卡车从魁北克千里迢迢运到了多伦多。遗憾的是，这家印刷厂质量不太灵：好多书里都有油墨还没干透涂抹的痕迹，不过还不算特别严重，至少字还能看清。我遗憾了很久，不过后来转念一想，也许这种与生俱来的不完美，正是纸质版魅力所在的一部分。

令人感动的是，直到五年后的现在，还有朋友记挂着这本书，给我发微博私信，询问什么时候能收到书。不能一一回复之余，还是希望将来能有机会，可以陆续再带一些书回国 —— 即使是不完美的「法拉利限量版」，也不能只有两百本是吧。

<div align=right>
2024 年 8 月，香港
</div>
