---
title: 读博的情怀
weight: 3022
slug: 好好学习天天向上/读博的情怀
目录:
  - 04好好学习天天向上
标签:
  - 2019年
---
> 尊敬的李老师，您好！我是您的书《幸福》的读者，目前在读电子信息专业的硕士研究生，明年就要毕业了，在未来道路选择的问题，想请教一下您的意见。目前我面临毕业后工作还是读博的选择，读博的话就在本校了，工作的话选项多一些，民营企业、国企这些打算都试试，主要是没考虑好要不要读博。我之所以读博，是周围亲戚和自己认为读书就一口气拿到最高学历，这样以后的晋升空间更大，前途选择也更多一些，但自己似乎也没什么学术理想，用不好听的话来讲就是拿个文凭。但是随着年龄的增长，觉得自己迟迟没有挣钱，加上得考虑更多现实问题，现在一直在犹豫了。周围人的观点都站在各自的立场上，所以希望老师能够给我一些意见，帮助我打开视野，谢谢您了！（问题来自微博私信）

##### 一

「读博」这个词儿，很容易让人误解。

首先，博士虽然是一个学位，但是它不像本科或者硕士学位，不是仅仅靠好好读书好好学习就可以读完的。精确的说，「读」虽然很重要，但「写」比「读」重要得多。而写文章，考验的不是学习的能力，而是创造和发现以前没人想过的新问题和新解法的能力。而创造和发现的过程，则比学习的过程难一些，也苦一些。

其次，博士的英文是「Doctor of Philosophy」，并没有「博古通今」或者「博采众长」等「广博」的含义。有一个成语叫「博大精深」，可是一个人的学问要想既做到「博大」又做到「精深」实在是很难的一件事儿。

能做到「博大精深」的我仅能想到两个例子。一个是我外公的导师赵元任先生，兼通语言学、哲学、物理学、数学和音乐，可以说是近代学者中「博大精深」的范例。还有一个是当今的风云人物 Elon Musk，当年他开创 PayPal 玩儿电子支付那会儿，支付宝什么的还没出生呢。开到一半儿大概他觉得不够好玩儿，靠看书自学火箭技术，继而开创尽人皆知的 SpaceX。英文有句俗语叫「It’s not rocket science」，用来表达「不是很难」的意思 —— 可见火箭技术很难。可想而知，把一个公司玩儿到火箭技术独步天下就更难了。

赵元任和 Elon Musk 之所以能做到「博大精深」，那是因为他们是天才。而如果「博士」只能「博大」和「精深」取其一，我们自然会偏爱「精深」。因为如果只「博大」而不「精深」，英文里叫做「jack of all trades, and master of none」，不是什么夸人的好话。而「精深」的好处在于，假以时日，无需天才，大多数人都可以做到。

所以，哪天你终于博士毕了业去相亲，一位好奇的女生问你研究了这么多年研究的到底是什么东西时，你当然可以泛泛地回答「人工智能」，或者「利用人工智能方法的语音识别」；但是如果你希望能精确一些，其实应该回答「基于五层以上深度神经元网络框架的低信噪比场景下高精确度短语语音识别」—— 因为你的研究以「精深」见长，在这个极其狭窄的领域中水平极高，但是出了这个领域你一窍不通。

当然，如果你善于聊天，可以这么给她介绍：「你玩过 Hey Siri 吗？」

##### 二

在你的担忧之中，提到了「挣钱」和「现实问题」。

这个简单：如果你觉得收入是一件比较重要的事儿，那应该选择不读博士。

这是因为除了少数大公司的研究部门，需要博士人才的工作 —— 比如大学教授 —— 工资普遍偏低，也没有股票和分红等其他附加收入来源，同时每年的工资涨幅普遍低于企业。

在企业里工作，提高收入的最好办法是跳槽到更加赏识你的地方。而这一条在学术界基本不灵：跳到其他学校涨不了什么工资，要想涨工资得离开学术研究，跳槽去企业任职。

当然了，这还没算为了读博士学位而少工作的这几年的沉没成本。

咱们可以粗略地估算一下。博士毕业假设你去高校工作，工资十万（人民币或美元），每年工资涨幅百分之二，工作三十年的全部工资加起来是 10 (1 + 1.02 + 1.02<sup>2</sup> + ... + 1.02<sup>29</sup>)，按照等比数列求和，这相当于 10 (1.02<sup>30</sup> - 1) / (1.02 - 1) = 405 万元。而如果你没有读博直接去工作，起薪二十万，每年工资因为跳槽等因素平均涨幅百分之五，工作三十五年的全部工资加起来是 20 (1.05<sup>35</sup> - 1) / (1.05 - 1) = 1806 万元，远远超过读博的总收入。

当然话又说回来，去企业工作一般没有「铁饭碗」或者「终身教授」一说，有一定失业的风险。如果失业时正好大环境就业也不景气，一直失业下去也不好说。

不过，我们可以计算一下在企业工作多少年收入才能和去高校工作持平：20 (1.05<sup>n</sup> - 1) / (1.05 - 1) = 405，解此方程得到 n = 15。也就是说，如果你 25 岁开始工作，只需要工作到 40 岁，总收入就可以超过去高校任职到退休 —— 你瞧，40 岁以后的都是净赚！

##### 三

当然，这些都是非常粗略的计算，因为收入和很多因素有关，无法一概而论。比如说，我们的计算里没有考虑到现在高校教职等从事研究的工作越来越难找，如果你那「精深」的研究领域正好没有空缺，就连找到第一个工作都可能成为一个问题。

比如十年前的一期《经济学人》杂志就曾经刊登了一篇文章，题目叫《为什么读博多半儿是浪费时间》（Why doing a PhD is often a waste of time）。

其主要的论点是：博士毕业生数量大增，而对博士生的需求相对疲软，很多非常优秀的学生与其去读博士，不如做点儿别的更有意义的事情。

你可能会问：说来说去，那到底什么样的人应该读博呢？

如果你看了我的这篇文字，清晰地意识到了所有读博的坏处和风险，对钱多钱少毫不在乎，反倒是对「基于五层以上深度神经元网络框架的低信噪比场景下高精确度短语语音识别」有一种偏执般的热爱，那你应该读博。

没错儿，读博士需要一种「情怀」，一种「明知山有虎、偏向虎山行」的执着，一种「西出阳关无故人」的悲壮。

因为对于有的人来说，旷日持久地去琢磨一件「精深」的问题，是一种让人开心的事儿，觉得一辈子没白活。

宁可飞蛾扑火，也在所不惜。

<div align=right>
2019 年 9 月，多伦多
</div>
