---
title: 《生活不是掷骰子：理性决策的贝叶斯思维》序言
weight: 3032
slug: 好好学习天天向上/序言
目录:
  - 04好好学习天天向上
标签:
  - 2023年
---

刘雪峰是我多年的一个朋友，他太能写了。继几年前写了一本《心中有数》，很快又要出版两本书：一本专门讲贝叶斯定理，还有一本讲科技论文写作。他邀请我给两本书各写一篇序言，我欣然答应，在香港去北京的高铁上完成了其中一篇。同时希望可以向他学习，将来多写一些文字。

<div align=right>2023 年 8 月 8 日 </div>

————

##### 一

关于读书，近年来有两种说法。一种说法是因为网络时代信息越来越碎片化，号召大家多静下心来读书；还有一种说法是，爱拿「读书」说事儿的人，都是一帮不学无术的半文盲，以为声称「爱读书」怎么着能够帮自己装得有文化有追求。

首先，我不是很喜欢「读书」这个词儿。本来「看书」这么一挺普通的事儿，一说成「读书」，就似乎成了一种需要沐浴更衣、正襟危坐才能从事的文化活动。

那在这抖音小红书的时代，看书是不是过时了？

我觉得答案其实挺简单的：这得看是什么书。

有的书吧，写的时候作者就想写成「著作」，看得艰深难懂，确实有点儿看不进去。

比如霍金的《时间简史》，当年风靡大江南北，可是我竟然没看完第一章。

又比如斯坦福大学的著名教授高德纳（Donald Knuth），图灵奖获得者，曾经历经数十载写了一部《计算机程序设计艺术》（The Art of Computer Programming），鸿篇巨制，到现在都没写完。我也曾经看过一章，就没能继续看下去。

但是也有的书，周末午后有个几个小时时间，就可以看个八九不离十，看完还觉得挺有收获，一时半会儿不会忘了。看这种书，我觉得真的可以贴切地用一个四字成语来形容：开卷有益。

我看这本书，就有一种开卷有益的感觉。

##### 二

「飞机正在剧烈颠簸，会不会出事儿？」

「对方微信回得不怎么积极，我该不该现在表白？」

五花八门各式各样类似这样的选择，我们每天都在做。

我们也经常把那些说话办事儿很靠谱的人归结到「情商高」的一类。确实，情商高的人，所做出的决策往往大多数都是正确的，可以省去很多烦心事儿。

可你有没有想过，其实所谓情商高，有时候就是一种准确的直觉。

而这种准确的直觉，其实是可以慢慢学习和培养的。

这里我有一个坏消息和一个好消息。

坏消息是，这个学习和培养的过程中，需要一点点数学思维。

这门数学就是概率论。

概率论虽然我们在大学都学过，但是学的时候背公式做题去了，学得快忘得快，直到后来全都不记得了。

可不巧的是，想培养这种「情商高」所需要的直觉，还得需要一点儿概率论。

这点儿概率论特别重要。重要到了其他部分的概率论都忘了都没关系，这一点儿概率论需要一辈子记得。

这点儿概率论就是贝叶斯定理。

不过还有个好消息。

贝叶斯定理虽然不容易理解，但是仔细想想，也不是特别难。

这本书的好处，就是可以结合很多生活中的例子 —— 比如点球大战守门员往哪儿扑 —— 让我们可以一个下午就把这点儿概率论想明白。

说不定，想明白了贝叶斯定理，我们就可以慢慢地领悟到这种情商高所需要的直觉呢。

##### 三

雪峰是我多年来的一个朋友。

他写这本书的初衷，我猜可能是希望我们在待人处事之中，不会是「一帮不学无术的半文盲」，而是真的不自主地用上点儿科学的思维方式。

在这抖音小红书的时代，真的从头到尾认真写本书，其实是挺费力不讨好的一件事儿。

雪峰把写书提高到了「人生意义」的层次 —— 他真心地觉得，写了书、有了读者，人生才真的有了意义。

一个周末的午后也好，地铁通勤的途中也好，这本书或多或少看一小段儿，比起刷抖音小红书，也许更加「开卷有益」。

「飞机正在剧烈颠簸，会不会出事儿？」

答案可以在本书中找到。

「对方微信回得不怎么积极，我该不该现在表白？」

无论回不回微信，都永远不要表白。

<div align=right>
2023 年 8 月，多伦多
</div>

