---
title: 极致的简单
weight: 5022
slug: 为祖国健康工作五十年/极致的简单
目录:
  - 06为祖国健康工作五十年
标签:
  - 2019年
---
前一阵子回国讲课，预定的行程比较紧张，只讲了一周时间，几乎每天上午都要上课。由于这次的课是第一次开设，需要大量时间准备。结果是每天从下午开始工作，晚饭后准备到晚上十一点，早上三点多起来继续，往往需要准备到七点钟离开酒店去上课之前。

即使如此认真地抓紧时间，要不是用上了「手写幻灯片」这一大法宝，其实备课时间还是远远不够。

比如说，如果幻灯片需要数学公式，最快的传统方法是用 LaTeX 排版，完成以后再以矢量图的形式拖拽插入幻灯片。准备五六张幻灯片排满数学公式，我尝试了一下，再快也得一个多小时。如果中间还要插入文字，或者把排版数学公式换成画示意图，时间大概需要成倍增加。

而一节课四十五分钟，需要至少二十至三十张幻灯片。「换算」成时间，要是按照传统方式设计幻灯片，五个小时估计都打不住。

手写绝大多数幻灯片，一个大问题是选择 iPad 里哪个 画图工具效率最高。尝试了 Procreate 等好几种可能，发现还是这几年常用的一款最好用：Paper。

Paper 好用不是因为它的功能多强大，恰恰相反，是因为它功能不多，但是每一个功能在设计上都用了心思。我所有的幻灯片一共就只用到了三种笔：粗笔、细笔、水彩笔。粗笔能不能再细一点儿？水彩能不能再透一点儿？不行。就连颜色我都全程只选红色、蓝色和黑色。

这就好像一家有点儿「小资」的馆子，把菜单简化到只有几个菜，点菜自然就不用千辛万苦地斟酌再三了 —— 反正每个菜都可以体现这家馆子的最高水平。

又好像苹果手表虽然功能多得目不暇接，但是真正能用到的却很少。倒是「看时间」这个最为重要的功能，与其戴苹果手表，不如戴一块卡西欧电子表。

极致的简单才能带来极致的高效。

一周时间我准备了十六节课，几百张幻灯片。一旦内容想好了，每张幻灯片只需要一两分钟就可以一气呵成，再用 AirDrop 迅速传到电脑上，心情愉快。即使在每小时三百公里疾驰的高铁上，因为心思全都集中在内容上，工作效率和在酒店几乎完全一样。

当然了，手绘幻灯片还有一大好处：图文并茂、色彩鲜明、与众不同，充分体现了一个完全不会画画儿的理工科中年教师对可望而不可及的艺术世界长期以来孜孜不倦的向往。

<div align=right>
2019 年 7 月，多伦多
</div>
