---
title: 模拟游戏
weight: 22
slug: 幸福/模拟游戏
目录:
  - 01幸福
标签:
  - 2020年
---
> 亲爱的李老师，关注您很久了，我很喜欢看您写的文字：言之有物，温和、有力，闪着带有理性的感性，让人看了很安心。
>
> 有个问题我挺好奇的，就是每次看您写的内容的时候，我总感觉仿佛您的生活里充满的都是积极的、快乐的、温馨的内容，好像那些负面的社会新闻从未吸引您的注意力，选择地隔离它们，也从不会因它们产生任何情绪的波动和思绪的停留。好像您的眼睛只看得到光明，看不到阴暗。比如最近几度上热搜的杭州杀妻案、各种少女失踪情杀案件、蒙冤入狱的人生等。好像那些骇人听闻的苦难、令人揪心的他人经历跟你的生活井水不犯河水，不会产生任何的联系。我有些困惑，是这样的吗？如果是，想知道您的观点。如果不是，想知道您的处理方式。
>
> 过去有段时间我想清楚一个道理，每个人的生活都有各自的忙碌，大部分的新闻热搜其实都跟我个人毫无关系。我可以毫不关心。这种不置可否的「自私」确实节省了很多精力。但是人是社会的动物，一个人的经历和见闻，不可能与社会割裂开，而且长此以往，会不会让人丧失共情力，变成一个冷漠的人呢？可是看这些新闻，会不会产生不必要的戾气？
>
> 身为二十来岁的年轻人，在这个信息爆炸的时代，我们该如何筛选过滤信息源，该如何管理自己的注意力和精力，平衡社会与我们个人的关系？如何处理那些负面新闻给我们带来的心理冲击（或者压根儿不关心？）（问题来自微博私信）

##### 一

假如你想买辆车，无所谓「颜值」，无所谓品牌，也不差钱，唯一的希望就是这辆车质量靠得住，可以开很长时间不用怎么修，应该如何选择？

无论如何，我建议你千万别去什么「汽车之家」之类的论坛。

因为如果你到这样的论坛上去调研一款车的质量，你会发现那里充斥着各种「吐槽」：比如刚开了两个月发动机开着开着就开始冒烟啦、变速箱动不动就「顿挫」啦等等，不一而足。你一定会得出一个结论：无论是丰田马自达还是保时捷法拉利，质量都相当不靠谱，非常容易坏。

甚至看得多了你还会感慨：十几年前买的车结实得很，没想到这年头汽车行业的质量越来越不靠谱了。

但是实际上恰好相反，汽车行业总体来说质量比十几年前提高了不少。现在无论你买什么车，即使是直接挑一辆好看的买下，质量也差不到哪儿去。

这是典型的样本选择偏差：绝大多数人平常开车开得好好的，完全没有必要到论坛上去郑重宣布「我刚买了辆丰田，开了三年没有半点儿毛病。」就好像到了医院你只能看到病人一样，到了汽车论坛上你也只能看到负面的「吐槽」。不能依靠研究汽车论坛来评估汽车品牌的质量，就好像不能因为流感有可能造成极小比例的病人死亡，就认为流感是一种极其可怕的传染病一样。

看社交媒体上的新闻，自然也是同样的道理。坏消息在新闻中延绵不断滚动播出，不等于世界末日即将来临。就像绝大多数新车不用担心质量问题一样，绝大多数人过的日子都早出晚归，买房买车，上学上班，几十年如一日，平淡无奇。其实即使是轰动一时的新闻，也一样会像火车车窗外的小站站台，昙花一现，一晃而过。试想，现在还有谁会再去关心马航 370 或者马蓉翟欣欣的下落呢？

几年前的一年年末，我去加勒比海坐了七天的邮轮，没有新闻，没有上网。

回来以后发现，没人找过我，也没有错过任何值得追溯的新闻。

##### 二

劲爆的新闻就像火锅 —— 越吃就越爱吃，爱吃的人多了，火锅店自然会雨后春笋般地冒出来。同样，越是惊世骇俗的新闻看的人越多；而为了看的人多，作者就要添油加醋推波助澜写成「爆款」，尽量让你也看到。再加上用手机看新闻和以前的报纸杂志不同，只要标题引人注目，「重磅」、「无敌」、「震惊」，再加上若干惊叹号，即使我自己也无法抵御它的诱惑，想点进去看个究竟。

本来这样的「标题党」「爆款文」并没有什么问题：人家也没有强迫我去看，我不看不就行了？哈哈，还真的由不得你不看：「爆款文」被亲朋好友转发「刷屏」，绝大多数人为了跟上这个时代的步伐，总还是会看一些的。看完了未必不会感慨万千或者义愤填膺，继续转发到自己的「票圈儿」。

久而久之，由于经典的「劣币驱逐良币」效应，写高质量文章的人只会越来越少。高质量的文章需要基于事实，心平气和，有理有据，逻辑清晰，几经修改而成稿，本来就很难写。好不容易写出来了，即使冠名为「深度好文」也一样不可避免其门可罗雀的命运。天下虽然也不是没有免费的午餐，但俯瞰外滩全景的午餐，是无论如何不会免费的。这样恶性循环下去，即使是朔爷复出，金庸转世，也无力回天。

那如何在「辣子」里找到那些宝贵的「鸡丁」呢？

很遗憾，由于大多数标题已经无法代表文章的质量，我还真的没有什么迅速有效的好办法。唯一一个我能想到的途径，是去关注极少数我觉得靠谱的偶像或朋友的微博。比方说如果褚老师公开发表了一篇文章，即使是广告，我都会先睹为快。

可惜芸芸众生之间，无论是偶像还是朋友，这样的人越来越少了。将来你要是偶然发现了好看的文字，发现了当年的辛夷坞、慕容雪村和醉钢琴，一定要推荐给我。

##### 三

你前几天有没有听说这么一条普通的新闻：微软发布了一款全新的游戏，叫 Microsoft Flight Simulator 2020。

这款飞行模拟游戏逼真到了什么程度呢？它真实地再现了全世界两百万个城镇，十五亿座建筑，还有三万多个机场。所有的天气、地貌和建筑都是根据真实情况实时渲染的：无论是晴间多云还是暴雨如注，在飞机座舱内的景色都和真实场景一模一样。高速公路上跑着模拟的汽车，雨后还会惊喜地看到彩虹。

这个游戏哪里还是游戏啊，简直就是一个全新打造完全真实的虚拟世界。

它让我想到了斯皮尔伯格的电影「Ready Player One」：在三维的虚拟世界里，我们一起慢慢长大，成为同生共死的亲密爱人和战友。

也许有一天，会有那么一个模拟游戏，可以让我全然忘记所有那些骇人听闻的苦难，那些令人揪心的场景，全心全意地进入一个幸福的虚拟世界。在那里，就像王朔在《一半是火焰，一半是海水》的结尾里说的，一路乘船、火车回家。在那里，我穿过广袤的国土，看到连绵起伏的著名山脉，婉蜒数千公里的壮丽大川，看到成千上万、随处可遇的开朗的女孩子。

<div align=right>
2020 年 8 月，香港
</div>

