---
title: 祝福
weight: 4008
slug: 长期共存互相吹捧/祝福
目录:
  - 05长期共存互相吹捧
标签:
  - 2021年
---

> 李老师您好，想向您请教一个问题。给朋友，长辈，老师或领导发节假日的祝福短信，如何做到不流于形式显得真诚不虚假？感觉祝福信息已经沦为了一个礼节性的过场，双方都认为是个虚假的客套。同时也祝您父亲节快乐。（问题来自微博私信）

哈哈，我最不擅长的就是发祝福短信了。为了更好地回答你的问题，我专门咨询了两位朋友：一位是国内高校的年轻老师，人又善良又漂亮；另一位是跟我差不多年纪的教授，朋友三教九流，多得满世界都是。

咱们假设，你发节假日的祝福短信是希望让对方记住你。但是由于逢年过节发祝福短信的人太多，你的祝福往往很难显得「特立独行」。而这种特立独行跟别人不一样的风格，正符合我一直推崇的做一个「contrarian」的哲学。我三年多前写过一篇《[逆水行舟](/post/% E5% A5% BD% E5% A5% BD% E5% AD% A6% E4% B9% A0% E5% A4% A9% E5% A4% A9% E5%90%91% E4% B8%8A/% E9%80%86% E6% B0% B4% E8% A1%8C% E8%88%9F/)》，说的就是这种哲学：

> 而我更钟爱的是一种逆水行舟式（contrarian）的风格：别人都买房我不一定买，别人都看武侠小说我不一定看，别人双十一都抢购我不一定抢，别人都玩儿朋友圈，我则自始至终「金盆洗手，淡出江湖」。

那发祝福短信这种小事儿，怎么「特立独行」，让别人更好地记住你呢？

我「锦囊」中的第一条建议，是「出其不意」。很多人每逢佳节，无论是农历新年还是端午中秋，都要发一轮祝福。这样的祝福短信自然不能群发，而需要给每一位领导或朋友「私人定制」，自然要花不少时间。但其实即使是跟相亲的对象也没必要每天都发信息问候，领导和朋友一年问候祝福一次其实足够了 —— 关键是这一次祝福哪天发。

本着「出其不意」的原则，发祝福最好的时间选择，是在对方的生日那天。生日是一个挺特殊的日子：它既有些私密，一般只有家人和最要好的朋友才能想得起来；又有些公开，即使不太熟悉，你要是打听一位朋友的生日，对方多半儿会很大方地告诉你。而现在大家都很忙，即使是平时叱咤风云的领导，每年的生日其实也不会有几个人能想起来。所以，你如果在生日这天准时发了祝福短信，文字简洁明快、情真意切，一定比农历除夕发同样的短信「特立独行」的多。

我的第二条建议，是「持之以恒」。我向美女教授咨询这个问题时她告诉我，她有一个现在已经毕了业的学生，找她的时候会给她发好长的信息，而没事的时候就音讯全无。我觉得这很常见，但正好是你体现自己「特立独行」的一个机会：如果你可以每年同一个日子都发一封祝福信，长此以往，十几年甚至几十年如一日，给对方的印象一定比大多数人要更加深刻。

但是为什么要局限于发祝福短信呢？我有一位同系的同事，每年的新年前夕都会给我发一封邮件，邮件里是一封精心设计制作、图文并茂的信。每年的信只有一页，但是包括了全家人过去一年中经历过的大事和去过的地方，还有一张全家旅游时的合影。他的「年终大事记」近十年来没有断过，看着孩子们一年年慢慢长大，让人不禁感慨光阴若白驹之过隙，岁月已蹉跎。

其实，如果是几位特别的朋友或者领导，按照我这位同事的思路，完全可以手写一张祝福的卡片，再附上几张刚洗出来的彩色照片，提前邮寄过去。「出其不意」得自然爆表，再能持之以恒，无论如何也不会成为「礼节性的过场」了。

当然，如果「出其不意」和「持之以恒」太麻烦，写情真意切的祝福文案又太强人所难，我的另一位朋友有一个建议：

发条「新年快乐」，然后转 6666 就行了。

哈哈，如果你哪天真的成了「财富自由」的土豪，想让人记住你很简单。

父亲节快乐。

<div align=right>
2021 年 6 月，香港
</div>
