---
title: 泯然众人
weight: 18
slug: 幸福/泯然众人
目录:
  - 01幸福
标签:
  - 2019年
---
> 李老师好！我本来是一个超级活泼开朗、无忧无虑的人。但是在经历了很多个突然长大的瞬间之后，我感觉现在的自己丧丧的，有种底色日渐悲凉的感觉，似乎快乐很难且很短暂。对于这种悲观，您有什么建议吗？（问题来自微博私信）

##### 一

日子过得不开心，自然有很多可能的原因。甚至有的时候，亲人或者朋友无心说出的一句话，听了都会让人觉得生活索然无味，世界黯然失色。

但是既然你的问题这么笼统，有一种可能的原因，我打算单拎出来掰碎一点儿聊聊。

我觉得身边的很多人 —— 也包括我自己 —— 从小到大受到的教育，都有点儿过于「正能量」。比方说，我们要有崇高的理想，远大的抱负，从师要「青出于蓝而胜于蓝」，无论将来做什么工作，都要「干一行爱一行」，「三百六十行，行行出状元」。我们生怕自己变成了「伤仲永」中的那个「泯然众人矣」的天才少年，生怕「做一天和尚撞一天钟」。

等到我们为人父母的那一天，带孩子则更是如此：巴不得把自己未竟的理想和抱负，将来让孩子来替我们实现。我们「可怜天下父母心」，为孩子找最好的学校、上最好的特长班，同时永远在羡慕别人家的孩子：怎么教育的，这也太优秀了吧。

但是很多时候我们发现，从上学到上班，从谈个恋爱到结个婚，真实的世界其实极其残酷：工作不顺心，领导不待见，甚至谈个恋爱都谈不成。「待到理想化宏图」似乎永远没戏，只有时间，在一年一年没有悬念地慢慢流逝。

偏偏这时候，「头条」里充斥着各种「大牛」的成功经历，朋友圈里则永远是「哪壶不开提哪壶」—— 我这儿还没男朋友呢，闺蜜都结婚了；我这儿论文不断被拒，人家的论文永远榜上有名，搞不好还能得奖。就连机场的书店里，随处可见的都是马云、冯唐、李开复这样的「人生赢家」，令人相形见绌。

这大概就是你所说的「突然长大的瞬间」吧。

##### 二

二十多年前我在清华上学的时候，同宿舍有一个室友，而且还恰巧睡在我的下铺，可以算是「睡在我下铺的兄弟」。

我发现我们班里的「神人」都有一个离奇的姓名 —— 我下铺的这位兄弟姓「银」，我们都管他叫「老银」。

老银虽然睡在我的下铺，但跟我完全不是一路人。我属于比较「追求上进」的同学 —— 每天晚上一定要去自习教室上自习，晚上十点准时下自习的那种。老银则是我的「镜面反射」：他从来不上自习，甚至不经常参加打牌或者踢球等一系列人民群众喜闻乐见的课外活动。

他的爱好时不时会变，但却永远别具一格。比如大二有一阵子，他喜欢修电视机。一位同学捡回来了一台没画儿了的黑白电视，他靠着一把老旧的电烙铁，愣是把这台电视给修好了。害得我十几年前买过的一台背投影的彩电后来颜色坏了，我第一反应竟然是自己打开后盖去修。

临近大学毕业时，班里的同学全体下馆子聚餐。像电影《致我们终将逝去的青春》或者《芳华》里的散伙饭场面一样，同学们频频举杯，依依惜别，男同学大多老泪纵横。据我观察，老银像没事儿人似的，冷眼旁观，不屑一顾。我的毕业纪念册上，「睡在我下铺的兄弟」没有留言。

我和老银明显不是「一条线上的蚂蚱」，毕业以后也就自然而然地失去了联系。每次老同学聚会时打探老银的消息，消息灵通人士寥寥。二十多年来，只是听说老银没怎么工作过，曾经迷过几年炒股，没有女朋友，后来辗转移民了加拿大。在加拿大也没怎么工作，据说这几年靠救济生活，白天喜欢在咖啡店闲着看看人来人往的风景，晚上则住在政府给无家可归者提供的住所（homeless shelter）。

据说有同学曾经问过老银，问他为什么不找个工作。他的回答是：为什么要工作？

一个清华的毕业生，在遥远的加拿大名副其实地「流落街头」，竟然过得还不错。有的人倡导「断舍离」，倡导「极简主义」，老银则把「极简主义」活到了极致，连个自己的家都给「断舍离」了。

心情「悲凉」的你一定会开心地发现，即使你将来「混」得再差，也比老银混得好些。

不过我一直觉得，老银像一位少林寺里扫地的和尚，武功卓绝，日子过得很牛逼。

##### 三

前几天去香港，跟一位香港理工大学的教授朋友吃饭。酒过三巡聊起香港时局，朋友说这几天经常会觉得一个人就像大海中的一滴水，像沙漠里的一捧沙子，风暴来临之际，只有随波逐流的份儿。

其实不需要挂什么「十号风球」，即使是风平浪静，我们绝大多数人也不可能出人头地，在历史的长河中，充其量也只不过是一朵浪花罢了。

每天买个菜，做个饭，朋友圈里点几个赞，在咖啡店喝一杯咖啡，看着窗外行色匆匆的人们，「比上不足、比下有余」，不是也挺让人满足的么？

那年我竟然把家里那台背投影的彩电修好了，后来又看了好多年。

<div align=right>
2019 年 11 月，多伦多
</div>
