---
title: 王牌
weight: 1026
slug: 将爱情进行到底/王牌
目录:
  - 02将爱情进行到底
标签:
  - 2019年
---

> 一月二十八日：李老师新年好！有个情感问题求助您。我和我的好搭档发生了地下情，他有女朋友我有男朋友。在最近一次热烈的出差后，在这些相处的过程中，我日渐感觉我想和男朋友分手而想和他正式在一起。但他也许不能和女友分手。我也不知道我的想法和感受是否正确，因为半年后我们就会结束搭档关系（我们说好地下情关系到搭档结束为止），我该怎么做？喜欢您的文字.....
>
> 四月一日：李老师您好，很抱歉再次打扰。之前向你请教的问题，其实已经算是解决了，当然也继而出现了新问题。原先的问题因为到了需要他担负责任的时刻，我也极不理性地告知了他的女朋友，所以他「逃跑」了，是真实的那种逃避。我心理上的痛苦是我现在的新问题。感谢李老师做了我的树洞。（问题来自微博私信）

##### 一

咱今儿个不聊爱情，咱们来学点儿英文。

两年前有一部电影叫做《Miss Sloane》不知道你看过没有，我看了不下五遍。主要是电影里面的英文对话密集得令人完全无法放松下来，像是上了一堂生动的英语听力课，看完了甚至觉得英语听力小有长进，还想再看几遍，「温故而知新」。

影片中的主角，Elizabeth Sloane，是一位「lobbyist」，一个专门为了阻止或通过一份法案去游说国会议员的工作。她在影片开场就说了一句名言，后来成为点睛之笔：

>Lobbying is about foresight, about anticipating your opponent's moves, and devising counter measures. The winner plots one step ahead of the opposition and plays her trump card just after they play theirs. It's about making sure you surprise them, and they don't surprise you.

而这段儿需要细细品味的话，最重要的是那句「plays her trump card just after they play theirs.」

什么是「trump card」呢？哈哈和特朗普没什么关系，英文里是「王牌」的意思，好像扑克牌中的「大王」，可以傲视群雄的那张。

##### 二

而你当初如果真切地希望那位男生为了你可以离开他的女朋友，也绝不能一厢情愿地空想，而是像「lobbyist」这个职业一样，把改变这位男生的想法作为一个重大专项来抓，做出一套切实有效的行动计划。

不过恐怕你一直心里很清楚，这个「逆水行舟」的计划即使可以做出来，可以按部就班地完美实施，这位男生离开他的女朋友的概率也不太高。

主要的一个问题是，他一直把和你的这段感情当成「地下情」来看，甚至还和你约定了到期的时间。你希望把「地下」情转到「地上」，就需要扭转他对你和你的感情的观点，螳臂当车，很不容易。

这时候如果你还希望能达到自己的目的，手中就必须要有一张「王牌」。不仅仅如此，你还要尽可能地预见到对方的「王牌」是哪一张。

「Lobbying is about foresight, about anticipating your opponent's moves, and devising counter measures.」你需要构想对方在你们俩这盘棋中所有可能的下法，然后一一构想应对之策。他无论如何布阵，都在你的意料之中。

而你的「王牌」，一定要在对方亮出自己的王牌之后才亮出来。你这一招制敌的路数，就好像金庸小说里说的：「独孤九剑，有进无退。招招都是进攻，攻敌之不得不守，自己当然不用守了。」

##### 三

可惜我的这篇文字还没来得及写呢，你已经把你的牌打出去了。而你出的不但不是「王牌」，没有「晓之以理，动之以情」，甚至竟是最糟糕的那张牌，仿佛你希望把你爱的男生推得越远越好。

不过，即使你很早就收到了我的建议，真的可以把这位男生当做一个假想的对手（opponent），把这个目标作为一个重大专项来制定一套详尽周密的计划吗？

不仅仅是你，我猜即使换了任何一个人，都很难把自己的情人当作一个头号对手，即使这样对实现自己的目标有帮助。

所以说，你和你心仪的男生再怎么「相见恨晚」，从一开始就无缘地久天长。

至少，在这以后很多年，每次睡着之前无端地想起这个人的时候，你可以对自己说：我爱过他，却从来没有像对待敌人一样，对他祭出那张早已准备好了的「王牌」。

<div align=right>
2019 年 4 月，多伦多
</div>
