---
title: 五星红旗
weight: 20
slug: 幸福/五星红旗
目录:
  - 01幸福
标签:
  - 2019年
---
> 李老师您好，我想了很久还是想要给您发这样一个私信。我是您在香港理工大学当访问学者时教过的 e-commerce 的研究生。读书的时候深深折服于您的学术成就以及任何时刻都能够化繁为简的教学技巧及非常具有感染力的个人魅力，微博有时看您给其他人答疑解惑也觉得十分受用。
>
> 众所周知，香港最近的种种令人感到痛心，特别是昨天今天理大发生的事件更是让人觉得匪夷所思，我觉得已经发展到了失控的地步。看到曾经生活学习过的香港变成如今的样子，感到十分难过。同时也不解，为什么香港会变成这样？香港还能好吗？十分想听听您对香港最近发生种种的看法，如果您能回复我会十分开心！但是如果有不便，您不能或不想发表意见，我也十分理解。无论如何，还是非常感谢您看完我写的这些，一直觉得人生路上能遇到过您这样的老师，是我的幸运，谢谢！（问题来自微博私信）

##### 一

收到你的来信觉得特别亲切。六年前在香港理工大学访问期间，我教的这门 e-commerce 学位的研究生课是我第一次在香港教书，所有教学内容都需要从头精心准备，可以算是别具一格的一次体验。课虽然是英文教学，我发现大多数的学生都是内地生，课上课下互动很多，教起来非常开心。整个学期认识了好几个经常来问问题的学生，有的渐渐成了朋友，甚至现在还在保持联系。

不仅仅是学生，访问期间我也结识了不少同系的教授，很快就和他们成了聊得来的朋友。有内地背景的，有香港本地的，也有加拿大人。大家平常一起在学校的餐厅海聊，参加系里组织的活动，去羽毛球馆打球，去星巴克咖啡店喝咖啡，去铜锣湾吃上海菜，去离岛区「行山」（hiking）。和内地背景的朋友说普通话，和香港本地的教授侃英文，大家都对我非常友好。听不懂广东话，我居然逐渐喜欢上了这个完全陌生的城市。

其实不仅仅是我自己，那位加拿大来的教授在香港理工大学工作了二十多年，既不会说普通话也不会说广东话，也一样很喜欢这个城市。他告诉我，他最喜欢香港的是这里中西方水乳交融的文化。就拿吃来说吧，香港无论西餐还是粤菜都相当地道，甚至有巴西烤肉和日本料理拼在一起吃的日料小饭馆。

我闲下来的时候，有时会在理工大学的校园里漫步。我很喜欢这里的红砖建筑，有点儿像南加州大学，建筑风格各异，但是颇有异曲同工之妙。很多楼都相连在一起，下雨天去什么地方多半儿可以室内到达。每栋楼本来各有自己的名字，但是大概是为了方便标注，一概以二十六个字母命名。我最喜欢的地方还是图书馆，一楼有大量可以随手翻阅的图书，内容涵盖天南地北。图书馆里还有一家咖啡馆，我经常坐下来边喝咖啡边干活儿。

如果说理工大学的图书馆一直是我的「三味书屋」的话，那我住的地方 —— 九龙塘的又一城就是我「百草园」。在这里可以尽情地「拔草」—— 从奢侈品店、名牌时装店到苹果店，一应俱全。没事儿的时候我喜欢在又一城电影院看电影，在滑冰场看别人滑冰，或者在一家叫 Log On 的商店徜徉 —— 那里各种小玩意儿一应俱全，设计精奇，特别考验自律能力。圣诞期间，苹果店旁边的圣诞树大得出奇，上面挂满了各种饰物，玲琅满目，节日气氛浓郁。

前几天，听说香港理工大学的图书馆被水淹了，星巴克早就给砸了，红砖建筑起火了，一所大学的校园成了攻防的战场。

又一城也未能幸免。据说里面的圣诞树给烧了，只得停业。

##### 二

就好像欧氏几何所有的定理都是基于五大公理推出的一样，做人也必须有一些最基本的底线和「公理」。所谓「公理」，就是无论每个人的立场和观点如何，全社会都一致同意它们是正确的。

而小学生守则里「遵守国法校纪，爱护公共财物」这条，则是做人的「公理」之一。

违背了做人最基本的底线的人，无论其初衷和目的，都不值得同情。

如果你说为了达到自己的目的，可以不顾做人最基本的底线，不用遵纪守法，那你和杀人犯强奸犯又有什么区别？

就如同在电影院大声打电话会影响其他人的道理一样，世界上从来没有过绝对的「自由」—— 在你强调自己打砸抢烧的「自由」的时候，也必定会剥夺其他人的自由。

当一座城市里说普通话都可能危及人身安全的时候，当一所大学里所有的内地学生需要集体紧急撤离的时候，这座城市和这所大学，不是变得更「自由」了，而是失去了自由。

当一家咖啡店、一辆小巴、一家银行、一个过街天桥、一个地铁站、甚至一所大学的校园都可以随时被当做「死物」砸烂烧光的时候，这个社会不可能安居乐业，只能人人自危。

当一个社会里有「黑衣人」可以藐视法律、可以嚣张到无故当街打人却无人敢管的时候，这个社会不是在进步，而是在迅速倒退。

我最喜欢的电影《肖申克的救赎》里，Red 谈起 The Sisters 时说过一句名言：「You have to be human first. They don’t qualify.」

##### 三

我经常试图理解「抗议者」的逻辑，但却无论如何也想不明白。

比如说，假设「抗议者」大获全胜，香港警察全线落败，再也出不来了。抗议者自己若是遇到人身威胁，打电话报警却没有任何响应，下一步再去找谁？

再比如说，假设「三罢」极其成功，几百万市民被迫全都上不了班上不了学。无人给超市送货，无人维护无线电话和网络，「抗议者」们如何生活、又如何通讯联络？

归根结底，大概「抗议者」们追求的理想社会，不外乎是他们自己可以不用上班、不用上学，但其他人则需要给他们保证供水供电、保证无线通信、保证衣食无忧。而警察则需要各司其职，给他们保障社会治安良好，但又不能管他们自己的违法行为。

我相信，如此「在电影院大声打电话」的「抗议者」们，自己一定觉得比内地生高人一等，一定觉得说香港广东话比说普通话「高级」。

也许他们应该去找一本美国六十年代民权运动历史的书 —— 对，就是他们热爱的那个美国 —— 看看什么才是真正的自由，什么才是真正的平等，而他们玩儿的，又是历史上什么人曾经玩儿过的。

##### 四

前几天去香港访问，正好路过香港理工大学的红磡湾校园。红磡湾校园离主校园有一小段距离，似乎没有受到破坏。那天天气特别好，蓝蓝的天空让人心情愉快。车等待红绿灯准备左拐时，隔着路边的树林，我远远地看到校园楼顶上有一面五星红旗，在迎着风飘扬。

没错儿，无论「抗议者」们的目的是什么，无论香港的局势将来有什么变数，香港永远是中国的一个特别行政区，飘扬的国旗也永远是五星红旗。

那首五十年代曾经脍炙人口的经典《歌唱祖国》所唱的，几十年过去了，还是这么令人心动：

&#8195;&#8195;**宽广美丽的土地**<br>
&#8195;&#8195;**是我们亲爱的家乡**<br>
&#8195;&#8195;**英雄的人民站起来了**<br>
&#8195;&#8195;**我们团结友爱坚强如钢**<br>

<div align=right>
2019 年 11 月，多伦多
</div>
