---
title: Think Different
weight: 3027
slug: 好好学习天天向上/Think Different
目录:
  - 04好好学习天天向上
标签:
  - 2022年
---

> 葆春老师，冒昧打扰您了，您接受跨专业学生的申请吗？如果接受的话，对于跨专业学生会更看重哪方面的能力呢？（问题来自微博私信）

##### 一

什么才是老师这个职业的最高境界？

我一直认为，老师的最高境界不是把一个资质甚高的学生培养得更加优秀，而是把一个完全零基础的学生培养成合格的人才。

比如我推崇备至的姜昆老师，他年轻大红大紫那会儿，收了一个比他更年轻的学生，连中文都说不利落，更别提说相声了。

没错儿，这个学生就是加拿大人、我们多伦多大学的杰出校友，时年二十四岁的 Mark Rowswell 同学。

简称大山。

大山后来果真成为了一名合格的相声和脱口秀艺术家。有多合格呢？我多年以前去看过大山的现场脱口秀，精彩纷呈，令人捧腹。今年春晚里有一段姜昆的相声，很多人说相声里学广东话的那段是抄袭大山几年前的一段脱口秀。

一位原来不会说中文的学生，牛到了竟然有人觉得是老师去抄袭学生 —— 这位老师的水平，可见一斑。

##### 二

但其实即使是姜昆老师，我猜也不是什么样儿的学生都收的。

这多半儿不是因为他挑剔，而是因为实在是「带宽」不够。

计算机网络中，带宽的单位是比特每秒，延迟的单位是毫秒。老师培养学生，就像一个低带宽高延迟的卫星网络。一个学生读一个博士学位，「延迟」大致是四五年，可以算是「高延迟」了。但是请注意，他的老师的「带宽」也是极其有限的：比如我的「带宽」大致是平均每年收两个学生，假设收到六十岁，那我的职业生涯也仅仅还能再培养二十个学生左右。

不仅如此，一般来说水平越高的老师，相应的「带宽」也越低。斯坦福大学「十年磨一剑」终于把他的 TeX 排版系统「磨」得完美无缺的 Donald Knuth，据说一辈子只带了二十八个学生。

正是由于「带宽」有限，像姜昆这样的优异师资其实是一种极其稀缺的资源。

这就是为什么我从来不是很理解为了招博士生去高校做广告这种做法的逻辑。「酒香不怕巷子深」，吸引学生我认为应该依靠口口相传，如果主动去做广告，岂不有一点儿「酒」其实也不怎么香的嫌疑？

十年前我曾经在微博中提到过，我的理想有三条：「每礼拜有功夫跑二十公里；赚回家的钱全给媳妇儿血拼刷卡给娃上学；哥已不在江湖，江湖还在传说他。」

##### 三

那大山作为一名「跨专业」的学生，需要什么样儿的素质，才能「天降大任于斯人也」、终将学以致用呢？

我觉得大概也有三条。

第一是愿意下苦工夫完整地做好一件事儿。

二十世纪最著名的数学家之一 Paul Erdős 说过一句名言：「数学家的工作，就是把咖啡变成定理。」

我在美国上学时的第一位导师是当时的系主任 Daniel Reed 教授。他跟现在的时尚明星马斯克差不多，都是每周一百小时的工作狂。我每周去他办公室开会，空气中永远有一丝淡淡的咖啡味儿。

注意，Erdős、Reed 还有马斯克的一百小时跟我们反对的「996」不一样，他们是为了自己喜欢的事儿工作。他们的工作，就像是舞蹈家练舞、钢琴家练琴一样，是为了把一件自己热爱的事儿 —— 比如证明一个定理或者开创一家公司 —— 完整地做好。

第二是有很强的交流沟通能力。

这有点儿像传说中的北京出租车司机，个个都是「侃爷」。你还别小瞧这「侃大山」的能力，据我观察，大多数人其实并不具备。「谈笑有鸿儒，往来无白丁」，无论是几位好友小聚，还是机场咖啡厅闲聊，都可以侃侃而谈，快意人生，这才是优秀的「侃爷」。

第三是喜爱写作。无论中文英文，中心思想明确，言简意赅，逻辑清晰，标点符号正确。

在微博里，我时常可以收到一些陌生人的留言和问题，需要公开回答。每次回答之前，我都会修改一遍问题本身的语言问题。在这个过程中我发现，大多数的问题都需要修改，只有极少数的问题是可以直接引用的。

还有，如果你写的文字不需要修改，说明你自己已经仔细地修改过几遍了。说不定，你属于那种愿意下苦工夫完整地做好一件事儿的人。

##### 四

十几年来，线上线下，我给国内高校上过不少课，本科生研究生的都有。

在课堂上，我不太敢按照常规中途停下来问学生：「有什么问题吗？」

因为，每次问这样的问题 —— 甚至是提出问题让大家解答 —— 结果都是令人有点儿尴尬的沉寂，直到我开始自问自答为止。

这样一件小事儿，见微知著，也许那些愿意提问或者回答我的问题的学生，已经非常出色了。因为他们打破了「人云亦云」——「人非云亦非云」—— 的成规，因为他们跟常人不一样。

如同苹果九十年代那个扭转乾坤的广告「Think Different」的开场白：「Here’s to the crazy ones.」

与其罗列三条，不如就这么一条。

就像我的学生王菲爱说的：想多了。

<div align=right>
2022 年 5 月，多伦多
</div>