---
title: 时间
weight: 5032
slug: 为祖国健康工作五十年/时间
目录:
  - 06为祖国健康工作五十年
标签:
  - 2022年
---
几个月前，有个朋友曾经提到回头会在微博上问我一个有关「时间管理」的问题。直到现在这个问题也没有等来，我想要不然先聊起来，等问题来了再行补充。

我一直觉得「时间管理」这个词儿不是很贴切：时间不是财产，无论咱是花还是不花，都会自然而然地流逝，实在是没办法「管理」。无论是「只争朝夕，力争上游」（也就是所谓「开卷」），还是「终日昏昏醉梦间」（也就是所谓「躺平」），都仅仅是不同人的选择和生活方式，很难说孰优孰劣，也很难评价「时间管理」的水平。

不过话又说回来，我当了二十多年的教授，确实经常有忙得时间不够用的时候。从这个角度来看，如何更有效地利用时间，还真是个亟待解决的难题。其解法众说纷纭，有人甚至设计了极其纷繁复杂的所谓「get things done」的系统，甚至看个电影吃个饭都纳入了「时间管理」的范畴。出于好奇，我还真尝试过一两次，结果发现需要花时间和精力去「管理」时间，还带来了不少不必要的焦虑，有些得不偿失。

我的博士是在伊利诺伊大学香槟分校读的。当年我读书的时候，有一位德高望重的老教授，名字叫 C. L. Liu。这位刘教授的重要贡献之一是一篇 1973 年的论文（Liu and Layland），首次提出 rate monotonic scheduling，算法简单而有效，成为实时操作系统中调度算法设计的里程碑。

我发现，rate monotonic scheduling 中有一些设计理念，同样可以用来「管理」时间。

这个算法有两个基本假设和一个核心设计。

一个假设是同一个时间只能做一件事儿，比如写论文或者编程的时候不玩儿手机。这个假设我觉得挺重要的，一段时间只做一件事儿，才能更加专注，质量更高。

第二个假设是优先级高的任务来了立即开始，优先级低的任务先暂停执行，比如男（女）朋友要叫个外卖，论文写作立即暂停，无论是否马上可以写完。

这个核心设计，就是采用固定的调度优先级（static priority）。这是什么意思呢？我们平常决定先做什么，一般是看这件事儿是否紧急，截止时间早的先完成。Rate monotonic scheduling 也是用的这一原则，但是它是根据不同任务的紧急程度先确定优先级，然后优先级高的先做，不再看截止时间。比如上级领导交代的任务，优先级相对更高，无论什么情况下，任务来了马上开始。

Liu and Layland 这篇著名论文证明了，用这样的算法设计，对时间的利用率无法达到百分之百。即使任务非常多，最多可以到 ln 2 (69%)。这就是说，有百分之三十的时间浪费了。看着挺差劲儿的，但是因为浪费的时间可以用来刷抖音小红书，其实可以算是生活工作三七开吧。

以「浪费」百分之三十时间为代价，优先级固定，高优先级任务来了立即执行，老板的邮件和微信秒回，这就是我的「时间管理」。

刘教授一辈子待人以诚，著作等身，培养了二十六位博士研究生。离开伊利诺伊大学以后，曾任新竹清华大学校长，两年前去世，享年八十六岁。

<div align=right>
2022 年 8 月，多伦多
</div>
