---
title: Trivial and Brilliant
weight: 3038
slug: 好好学习天天向上/trivial-brilliant
目录:
  - 04好好学习天天向上
标签:
  - 2025年
---
>感谢老师的微博分享，以后我也会更加注重套瓷信的独特细节。
>
>我是电气工程专业博士生，曾反复听过您的讲座「Writing Prefect Papers」，受益匪浅，也因此发表过几篇 SCI 论文。部分工作发表在中科院一区 TOP 期刊，但也意识到自己的工作是增量式的（「灌水」），并没有很强的创新性以及理论和工程价值，能发表其实有很大运气成分。
>
>我近期去外地参加了一个数学系的优化与运筹的短期培训，发现了一个很小众的领域，在我们专业的文献更是寥寥无几。但是做小众的工作风险也显而易见：即使投入大量的时间和精力，也极有可能是失败的，一将功成万骨枯。与其这样，可能还不如「灌水」，增加论文的数量，或许利于找工作。
>
>请问老师，您怎么看待论文的质量与数量的关系？谢谢！（问题来自微信）

##### 一

我所在的多伦多大学电子和计算机工程系，每年都有一两个计算机工程领域的教职空缺。

我们的面试分为两轮。而第一轮线上面试的问题，一般会提前一两天分享给面试者，可以有针对性的准备。

这里开门见山的第一个问题是：

Can you discuss a recent paper that you are particularly proud of?

「请你介绍一篇自己最引以为豪的论文。」

注意，这里明确说明是一篇论文，而不是几篇。也就是说，即使你有一百篇论文，也请你自行选择其中一篇，给大家讲一讲，这篇论文为什么可以代表你的最高学术水平。

这个问题很明显不是我们的独创，甚至是老生常谈的一个问题。早在 2004 年，我去普林斯顿大学开一个学术会议，开场的基调演讲是信息论领域 MIT 的著名教授 Bob Gallager。他的演讲中就提到，评价一个申请教职的候选人，应该看其最出彩的那一篇论文。

可以说，1960 年时的 MIT，就是因为采用了这个评价标准，才会破格录用了 Bob Gallager 本人当助理教授。他当时的博士论文，提出了信息论领域中石破天惊的低密度奇偶校验码（low-density parity-check codes），但是该论文直到三年后才发表。

你的问题中提到，你有好几篇 SCI 论文已经发表。

这种说法很常见：很多年轻学者开会上见到，自我介绍时也会说自己有多少多少篇「CCF-A」、多少多少篇「顶会」论文。

我想，他们要是真的去找 Gallager 老爷子索要推荐信，他一定会问：

你最出色的一篇论文是哪一篇？

##### 二

我自己的学术生涯中，也写过好几百篇论文。

其中印象最深的一篇，二十一年前发表在一个名不见经传的学术会议上。这个会议是在我母校 UIUC 附近的一个叫做 Allerton 的小地方开的。我没有查过，但是我觉得大概率连 CCF-C 的会议推荐列表都没上。

而这篇论文呢，其实没有做出任何贡献：它既没有证明任何定理，也没做任何实验。按照现在的高标准，甚至连发表都有点儿难。

这篇论文仅仅是提出了一个猜想：网络编码在一对一的单播网络流（unicast network sessions）的场景下，相比不用网络编码，没有任何优势。

这篇我和我当时的学生、现在任教于清华大学的李宗鹏教授合作完成的论文，后来在编码理论圈内叫做「李和李猜想」（the Li and Li conjecture」。

很多学者研究过这个猜想。但即使是在二十一年之后的现在，也仍然没有被攻克。

乔布斯九七年回归苹果时，把所有的项目负责人叫到他办公室，问了几个问题。其中第一个问题是：「如果资金不是问题，你计划把你的项目发展成什么样儿？」

同样的问题你也可以自己问自己：如果钱不是一个问题，你希望如何利用自己的宝贵时间资源，做什么样的研究？

比如，你会不会也给世界提出一个猜想，简单得出奇，却无人能够解决？

就好像图灵奖得主 Jim Gray 评价同样也是图灵奖得主的 Leslie Lamport 写的一篇题为「Time, Clocks and the Ordering of Events in a Distributed System」的著名高引论文时说：

It’s trivial, and it’s brilliant.

##### 三

那如果你看着自己的论文，实在找不出一篇自己觉得拿得出手的，怎么办？

答案很简单：现在开始写也完全来得及。

当然了，「钱不是万能的，但没有钱是万万不能的。」生活所迫，我们大概都需要占用大量时间，写一些自己都觉得没什么价值的论文。

可当晚上孩子终于酣睡时，嘈杂的高铁站里等车时，航班上刷剧没有网络时，我们能否利用这些空闲时间，少刷点儿抖音小红书，一鼓作气，励精图治，铺开四百字的稿纸，开始写一篇自己引以为豪的论文呢？

这篇论文，可能需要五年，也可能需要十年，但是它将来终于完成时，你可以自豪的宣布：这是你最精彩的一篇论文，没有之一。

比如我自己，最近五年来，就在写这样一篇论文。

这篇论文提出了一个全新打造的仿真平台，可以将传统离散事件网络仿真的速度，提高二至三个数量级。也就是说，原来几小时才能完成的仿真，现在只需要几秒钟。不仅论文全文是我亲自一个字一个字撰写而成，而且其绝大多数代码，短小精悍，「麻雀虽小，五脏俱全」，也是我几年来在酒店里，在航班上，一点儿点儿亲自设计实现的。可以说，这篇论文对应的系统实现，已经代表了我自从中学学习计算机编程以来的最高水平。

我想，审稿人看完了论文，如果因为「it’s trivial」而拒稿的话，我会回答他：

But it’s brilliant.

<div align=right>
2025 年 7 月，香港
</div>
