---
title: 信任
weight: 7025
slug: 柴米油盐酱醋茶/信任
目录:
  - 08柴米油盐酱醋茶
标签:
  - 2020年
---
> 李老师，您好，元旦快乐。辞旧迎新的年底，是我比较纠结的时候，想问问您的意见。
>
> 我和男朋友是做教育培训的，不是正式的公司，两人一起合作招生。学生的学费都是转到他的支付宝账号里，一年结束，我真的很想让男朋友理一下把钱分了，这是我付出一年应该得到的。我之前试探过他，他的意思是在一起了，钱也应该在一起。
>
> 作为女生我比较希望自己经济独立，买车买房可以一起还，但是退一万步讲，离开你我依旧可以过得很好，不想依赖谁。我不知道该如何沟通关于钱的事情？让他明白又不伤害感情，我是爱他的，但我觉得这是两回事，独立与爱他并不冲突。
>
> 辛苦您了，新年快乐！（问题来自微博私信）

我的缺点之一是，不够大度，小家子气。

所以我建议：斩钉截铁地立刻摊牌表明立场，把你自己的那部分收入从他的支付宝账号要回来。

他越是找理由不给你，你就越要仔细留意他不给你的理由。如果他的理由像你说的是「既然在一起了，钱也应该在一起」，怎么办？

哈哈那你可以回应：「那就把所有的钱都转到我这里好了。」

他的逻辑中有一个明显的问题。把两个人的钱放在一起当然很好，但是必须是共同拥有的账号。在加拿大，共同拥有的私人账号（joint account）非常常见，很容易开，把两个人的名字都写进去就可以了。当然还有一个办法是注册一个公司，两个人都是公司的股东，共同拥有公司的财产。

如果不是共同拥有的账号，那可不是「在一起」的钱，而是他一个人的财产。按照这个逻辑，把所有钱都转给你，岂不是也符合「在一起」的定义？如果他找出种种理由不愿意全都转给你，那他的「在一起」的逻辑则完全站不住脚，不攻自破。

那如果将来你们确实生活在一起了，钱应该如何保管才是最优策略呢？

不知道你是否听说过，计算机上运行的操作系统中有一个概念，叫做「线程」。在程序运行的过程中，两个线程既共同拥有一些全局变量（global variables），又各自拥有各自的私有变量（local variables）。

两个人在一起其实也可以这么过日子。既各自有各自的账号，又同时拥有共同的财产，这样有百利而无一害。其实对大多数家庭来说，与其说是「共同财产」，不如说是共同的负债，因为两个人需要一起还房子的贷款。贷款越早还清，支付的利息总额就越低，所以每月开销的盈余，大部分其实都拿去还贷款了，两人各自的账号其实也仅仅只是一点儿「私房钱」，也就够时不时给对方买个礼物罢了。

如果是在国外，两人各自的账号还包括退休储蓄。因为退休储蓄账号（比如美国的 IRA 或加拿大的 RRSP）可以少交税，理论上就又复杂了一个层次。比如，收入多的一方可以把钱存入收入少的一方的账号中，叫做「income splitting」，可以最大程度省税。

钱在各自的账号中，既可以互送小礼物，又可以一起还贷款，一起研究如何储蓄、如何投资、如何省税，两个人小日子不是也挺红火？

电影《肖申克的救赎》中 Andy 在狱中的转折点，源于他对狱警 Mr. Hadley 说的一句话：

>Mr. Hadley, do you trust your wife?

<div align=right>
2020 年 1 月，多伦多
</div>
