---
title: 两地
weight: 7037
slug: 柴米油盐酱醋茶/两地
目录:
  - 08柴米油盐酱醋茶
标签:
  - 2024年
---
> 想请教朋友们一个关于人生选择的问题，希望大家不吝赐教。问题是：我该为了家庭放弃编制吗？
>
> 背景：我是一所小学副科老师，算上公积金年入 30 万，自己专业水平一般，现在工作是我人生的天花板，放弃编制去社会上找工作估计是个噩梦。孩子爹学历还行，跟随团队在另外一个省的新型科研单位做人工智能，收入比我高，他过来我这里的话又很难找到对口的方向。
>
> 我们婚后一直异地，他回家频率是每月 1-2 天。现在孩子快读小学了，很多问题在长期异地中越来越凸显，所以我一直想着要不要辞职过去那边结束异地。我年龄快超龄了，再备考事业编也没啥希望，很难割舍下现在的工作。现在我到底该怎么办？（问题来自「葆春和他的朋友们」）

无论如何选择，你不要选择辞职。

假设有两份工作：一份工作非常稳定，没有什么风险，无论大环境如何变迁，都可以保证或多或少一份工资，但是收入比较低。

还有一份工作，收入相对高一些。将来的收入甚至有可能更上一层楼，但是随时都有可能被解雇。再找工作的风险相对比较大，不一定可以找到和自己能力和专业背景匹配的工作。

你觉得应该选哪一份工作呢？

在你的具体事例中，结束长期异地的方案有两种：一种是你辞职，一种是他辞职。咱们假设没有其他因素影响你的选择 —— 比如地理位置哪个更优越 —— 应该如何选择呢？

这个问题其实在另外一种人才市场中，有很多人做出过选择。

这就是具备博士学位且成绩出色的应届博士研究生毕了业，是去学术界做研究还是工业界研究机构的选择。

大多数毕业生，都会优先选择学术界，即使学术界的收入比工业界低得多。

原因虽然各异，但是其中之一是因为学术界一旦几年后拿到终身教职，基本上可以算是「铁饭碗」。

当然也有选择工业界里的研究岗位的 —— 甚至有学术界已经拿到终身教职的教授，跳槽去工业界发展的。但是这需要一定的激励机制，而最重要的激励当然就是收入。据我粗浅的估计，工业界的收入至少要到学术界收入的三倍 —— 也就是税后收入的两倍 —— 以上，工业界的研究岗位才开始有竞争力。甚至这还得是在跨国高科技大公司，收入相对稳定，被解雇的风险相对比较低的情形。

细心的读者会发现，我刚才讲的是一个人自己面对两种不同工作的选择，你的情况则略有不同。你的选择中，还包括了辞职后是否能找到新工作的风险。你辞职后顺利找到新工作的概率，明显低于他辞职后找到新工作的概率，选择的天平在向他辞职倾斜。如果我们同时考虑工作本身的稳定性和顺利找到新工作的概率，他的工资可能需要比你的工资高好几倍，才有可能开始认真考虑你辞职这种选择。

显而易见，以上分析都是假设你们两人可以以平等而客观的角度，逻辑清晰、按部就班、就事论事地讨论这两种方案的选择。讨论的过程中，更看重中长期的风险规划。因为一般来说，随着时间的推移，家庭开销会逐渐上升，未来的收入和失去该收入的风险，都需要仔细考虑。

你可以看到，我的观点是纯粹地从收入角度来看的，而没有提及孩子。这是因为我假设，无论孩子在哪里上学，只要异地的问题解决了，结果完全一致。如果两地中有更好的选择，我们当然可以继续给选择的天平加上权重，做一个加权的优化问题。

如果咱们可以客观地看这个优化问题，我觉得结论没有异议：与其选择你辞职，不如选择他辞职。

<div align=right>
2024 年 3 月，多伦多
</div>
