---
title: 看不见摸不着
weight: 5025
slug: 为祖国健康工作五十年/看不见摸不着
目录:
  - 06为祖国健康工作五十年
标签:
  - 2020年
---
> 葆春老师您好，我是一个不知名大学的本科的文科生。我父母文化不高，高考填志愿时不会帮我选专业，结果调剂到了我不喜欢的文科专业 —— 酒店管理。
>
> 我挺羡慕理科生的。理科生可以自然而然地毕业后从事自己专业的工作。
>
> 我一直都是个没有目标的人。我好像从未对什么提起过很大兴趣，我也不是个勤奋努力的人。
>
> 今年就要毕业了。我想去上海，但我不知道自己到底可以做什么。我想过考研，但也没有明确的考研目标，我真的很迷茫。
>
> 我很后悔自己以前的选择，这两年来都沉浸在痛苦中，非常希望葆春老师能指点一二，谢谢葆春老师，盼复。（问题来自微博私信）

我以前在引用一个打算回答的问题时，问题中所用的语言和标点符号，一般都会粗略地修改一遍。比如有的人喜欢用很多逗号，经常一句话特别长。我会把问题中的一部分逗号改成句号，再多分几个自然段，让问题更加清晰易读。

看了你的问题，我发现无论是语言还是标点，通篇竟然没有一处需要修改。我喜欢你的问题中每个自然段里第一句话不用逗号，而是直接用句号结束。这样表达更加简洁明了，颇有古人「环滁皆山也。」的开门见山，我一看到就挺有好感的。可以说，我喜欢你这个「不知名大学本科的文科生」的文风。

那咱们就步入正题吧。

##### 一

我小的时候有一种说法，叫「学好数理化，走边天下都不怕」。高中时，很多学习成绩不错的同学都对理工科趋之若鹜。大家高考考的都是「理工农医类」的考卷，班里学习最好的同学报的是北大生物系，而前几名的同学也清一色地都报了理工科。我上大学的时候，清华还是一所以工科为主的大学，我学的虽然是计算机，但学过金工实习，学过机械制图，感觉毕业了随时可以分配到大中型企业当一名工程师。

然而不知你发现没有，国外很多大学的惯例是将文科和理科归入同一个学院，工科则归入另外一个学院。与其分为「理工科」和「文科」，不如分为「文理科」和「工科」更为贴切。加州大学伯克利分校更加别出心裁，把文理学院叫做「College of Letters and Science」，一个学院涵盖了从文学到音乐到历史到经济到生物的方方面面，涉猎之广，令人目不暇接。

所以可以这么说，文科 —— 也就是伯克利的「Letters」—— 至少和理科是可以相提并论、分庭抗礼的。那这个「Letters」到底毕业后有没有用、是不是白学了呢？

我很晚才领悟到，其实这个「Letters」说不定比金工实习机械制图比当年热门的金融和生物 —— 甚至比从二十多年前到现在一直热门的计算机 —— 都更加有用。

原因很简单：跟金工实习或者计算机都不同，文科学的很多东西，属于「看不见摸不着」的技能。正是这种飘忽不定的感觉，让很多人觉得时间白白浪费全都白学了，毕业了也不知道要干什么好。可如果从长远来看，也正是这种「看不见摸不着」的技能，才能真正左右一个人长期的职业发展。

我喜爱的电影「Jerry Maguire」和「Chicago」中的女主角 Renée Zellweger，刚上大学时学的是英语文学（English Literature）。上了一阵子她开始选修戏剧表演方面的课程，后来毕业后参演了一些小成本制作的电影。共和党著名参议员 Mitt Romney 在去哈佛大学学法律之前，本科学的也是英语文学。

那他们的英语文学是不是白学了呢？从「看不见摸不着」的角度来看，我觉得非但没有白学，还造就了他们后来的事业。如果他们本科时学的是工科，那说不定现在也只不过是在一家大公司的研发部门供职，而不会成为好莱坞星光大道中的一员，不会成为政坛的一代枭雄了。

乔布斯零六年在斯坦福的演讲中说：「You can’t connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.」

英语文学也好，酒店管理也罢，或许越是没什么用的文科，就越没有白学。

##### 二

所以说，学什么专业干什么工作是「有用」的，还真的不好说。

1873 年，美国纽约有一个二十出头的小伙子，叫 Frank W. Woolsworth。一天，他衣衫褴褛地去应聘一家商店的营业员职位。老板跟他聊了一会儿，对他说：「行了，你下周一来上班吧。」 他非常开心，连忙问：「那我能拿多少工资？」 老板大叫道：「工资？你还想拿工资？我教你怎么做生意，你应该反过来给我发工资！」

那时候美国的劳动法还没有最低工资保护有关的条款，Frank 得以顺利得到了这个头三个月不拿工资的工作。头几年他确实很辛苦，每天只能打扫卫生，早上七点干到晚上九点，大家都瞧不起他。后来，他逐渐开始揣摩商品摆放位置和定价的门道，终于投资了几百美金，跟几个合伙人成立了一家以自己名字命名的「初创」公司，开了自己的第一家商店。他的生意越做越大，连锁店开始遍布全美，继而又遍布全世界。1913 年，他的公司在纽约曼哈顿建成了当时全世界最高的摩天大厦。

试想，如果当年的 Frank 看不上这个既不发工资又要打扫卫生的工作，大概就悟不出来后来得以大获全胜但却转瞬即逝的商机了。公司成功之后，他果然很感激当年的老板给了他这个不拿工资的工作，还请这位老板到他自己的公司来当合伙人，「反过来」给他发了工资。

这样「励志鸡汤」的例子自然俯拾皆是。年逾九十的斯坦福大学著名经济学家 Thomas Sowell 在他的著作《Applied Economics》中认为，无论是上学、看书还是工作，都是一个获取新的知识和掌握新的技能的过程。像在给自己「投资」一样，是一个积累「human capital」的过程。Sowell 提到：

>The growing importance of human capital tends to create greater income inequality between those people who have been assiduous in acquiring knowledge and mastering skills and those who have not. It tends to create greater inequality between those who work and those who do not.

他的意思是，只要学点儿什么干点儿什么，永远比什么也不学什么也不干天天打「王者荣耀」强很多。

如果你还是觉得自己的学业和工作一时半会儿没有什么用处，那就想想 Frank Woolsworth —— 他当年「初创」了公司，结果开的第一家商店很快就倒闭了。

放心吧，只要多运动增强免疫力，人一辈子有的是时间。

##### 三

当然了，要想「学点儿什么干点儿什么」将来有用，你学的东西一定不能是别人强加给你的，得是自己感兴趣的。如果是别人强加的，换了谁都很难做到长期「勤奋努力」—— 你瞧，连李开复都明白要「追随你的心」。

如果你想来想去，除了打「王者荣耀」和看「乘风破浪的姐姐」，怎么也想不出还对其他什么东西感兴趣，那怎么办？

我建议，竭尽心力，自己设计制作一样需要一两个月时间才能做好的玩意儿。

一两个月时间不算太长，但也不太可能一蹴而就。

你提到正在考虑读研的可能性。读研的过程虽然千差万别，但是都有一个共同的特点：要毕业就得写几篇论文。

虽然写出来的论文本身多半儿没什么用处，然而一篇论文就像一座雕塑，每一笔每一划都是自己设计制作出来的，都是自己的呕心沥血之作。在这个过程之中得到的「看不见摸不着」的技能，意义远远超过论文本身。

如果你对写论文不感兴趣，那就拍一部微电影，上线一家淘宝店，写一本书，开一个线上直播，修好一辆没人要的旧车，或者实现一个网站。

注意，去云南大理旅行或者种一株玫瑰送给男朋友不能算 —— 花点儿钱或者浇点儿水就行，太简单了。

比如我这两个月，就竭尽心力，从头学起，花了所有的业余时间和所有周末，实现了一个全新的网站。

其实这跟跑马拉松差不多 —— 虽然没什么用，过程也很艰苦，但大功告成之后，我看着网站背后的每一行代码，感觉每一个字节都在我的指挥下跳动，觉得非常过瘾，感到了一种「更上一层楼」般的快乐。


<div align=right>
2020 年 6 月，香港
</div>

