---
title: 张戎
weight: 4007
slug: 长期共存互相吹捧/张戎
目录:
  - 05长期共存互相吹捧
标签:
  - 2019年
---

> 张戎老师上微博吗？想关注这位牛逼的老师。（问题来自微博评论）

张戎虽然不怎么玩儿微博，却有一个 [知乎帐号](https://www.zhihu.com/people/rong_zhang/)，里面有不少精品长文，主题涉猎颇广。他文风独到，很多文字看起来是随心所欲一蹴而就，但其实是精益求精仔细琢磨过的，很值得一读。

他的知乎长文中我最为偏爱的一篇，回答的是这么一个问题：[有哪些十分钟就能学会并终生受用的生活技能](https://www.zhihu.com/question/20894671/answer/376383314)？

这个问题其实挺难回答的，反正我自己想了半天没想出什么比较像样的答案来。张戎的文章开门见山，直奔主题 —— 我直接引用几段吧：

> 当然要有 Alfa-Bravo-Charlie!
>
> 你在电话里跟老外拼读自己姓名的时候，有没有一种鸡同鸭讲的感觉？
>
> 扯着脖子喊话好几遍，还是 Z-C-V 不分，B-D-P 混淆。即使对方把字母组成单词来确认，如果信号不好还是分不清「 Bob」还是「Dog」，对吧？

我第一遍看的时候，简直有一种眼前一亮的感觉。每次电话里对方问：「Can I have your name, please?」我就有点儿紧张。「B as in … “Bob”, N as in — “Nancy”?」

再看下去，张戎就开始了他的「营销」：

> 你看一下 Alfa-Bravo-Charlie 这套标准单词，能不能花 10 分钟背下来，将来每次电话拼读英文姓名地址电邮都能省掉 2 分钟「B！B！B！不是 D！」的呐喊时间，5 次电话就回本，划算吗？

这篇文章我看了好几遍，还真花了不少时间 —— 绝对不止十分钟 —— 把这套「国际无线电通讯拼读字母表」背了下来。不久之后果然派上了用场，电话中信心百倍地回答：「B as in Bravo, A as in Alfa, …, and N as in November.」

一篇文章的结尾就像平衡木体操中的下法一样，极其重要。让我们来欣赏一下张戎这篇文章的「下法」：

> 大家知道英文中字母表这个词（Alphabet）实际上是希腊字母表头两个字母 Alpha 和 Beta 组成的。对于国际无线电通讯拼读字母表这个东西，与其取那个容易和国际音标（International Phonetic Alphabet）混淆的简称（NATO Phonetic Alphabet），还不如干脆叫「Alfabra」来得简洁性感。

<div align=right>
2019 年 11 月，多伦多
</div>
